//! Turning one IBIS buffer model into a SPICE subcircuit.
//!
//! An IBIS model is a set of measured tables, and a simulator wants a
//! subcircuit. The conversion fills in a template shipped with the
//! application rather than building the subcircuit from nothing, so what this
//! module decides is which model to convert, what to say about it, and under
//! what conditions the conversion can go ahead at all.

use crate::ibis::{IbisError, Model};

/// The template the conversion fills in, found under the SPICE library
/// directory.
pub const TEMPLATE_FILE: &str = "IBIS Models.dat";

/// The directory, relative to the application's own, that the template lives
/// in.
pub const TEMPLATE_DIRECTORY: &str = r"\SpiceLib\";

/// The decimal separator the generated netlist must use.
///
/// SPICE reads a comma as a field separator, so a netlist written under a
/// locale that spells decimals with a comma would be silently wrong rather
/// than rejected. The conversion therefore forces the separator for its whole
/// run and puts back whatever was there afterwards — see
/// [`DecimalSeparatorGuard`].
pub const SPICE_DECIMAL_SEPARATOR: char = '.';

/// The line the generated netlist opens with.
pub const GENERATED_BY: &str = "* Generated by TINA";

/// Holds the decimal separator at the one value SPICE accepts, and puts the
/// previous value back when it is dropped.
///
/// The recovered conversion saves the separator on entry and restores it on
/// every exit including its failures, so a conversion that gives up part way
/// through still leaves the application's formatting as it found it. Tying
/// that to a guard is how this port keeps the restore attached to the exit
/// rather than repeated at each one.
#[derive(Debug)]
pub struct DecimalSeparatorGuard<'a, H: SeparatorHost + ?Sized> {
    host: &'a mut H,
    previous: char,
}

impl<'a, H: SeparatorHost + ?Sized> DecimalSeparatorGuard<'a, H> {
    /// Forces the separator, remembering what it was.
    pub fn acquire(host: &'a mut H) -> Self {
        let previous = host.decimal_separator();
        host.set_decimal_separator(SPICE_DECIMAL_SEPARATOR);
        Self { host, previous }
    }

    /// The separator that was in force before.
    #[must_use]
    pub const fn previous(&self) -> char {
        self.previous
    }
}

impl<H: SeparatorHost + ?Sized> Drop for DecimalSeparatorGuard<'_, H> {
    fn drop(&mut self) {
        self.host.set_decimal_separator(self.previous);
    }
}

/// The application-wide number formatting the conversion borrows.
pub trait SeparatorHost {
    /// The separator currently in force.
    fn decimal_separator(&mut self) -> char;

    /// Puts one in force.
    fn set_decimal_separator(&mut self, separator: char);
}

/// Which name the conversion should look the model up under, and in what
/// order.
///
/// Part of Ghidra function `FUN_01bbf630` at `0x01BBF630`.
///
/// The pin names a model and the caller may name a different one. The pin's
/// own name is tried first and the caller's only as a fall-back, so naming a
/// model explicitly does not override the pin — it rescues a pin whose model
/// is missing from the file.
///
/// When the caller names nothing the pin's name stands in for it, which is
/// why a failure can report the pin's model name even though the caller
/// supplied none.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModelLookup {
    /// The name tried first: the model the pin refers to.
    pub preferred: String,
    /// The name tried second, when the first finds nothing.
    pub fallback: String,
}

impl ModelLookup {
    /// Works out the two names from the pin's model and the caller's.
    ///
    /// Part of Ghidra function `FUN_01bbf630` at `0x01BBF630`.
    #[must_use]
    pub fn new(pin_model: &str, requested: Option<&str>) -> Self {
        Self {
            preferred: pin_model.to_owned(),
            fallback: requested.unwrap_or(pin_model).to_owned(),
        }
    }

    /// The name a failure reports.
    ///
    /// The recovered code reports the caller's name rather than the pin's,
    /// which for a caller that named nothing is the pin's name anyway.
    #[must_use]
    pub fn reported_name(&self) -> &str {
        &self.fallback
    }

    /// Resolves the model, trying each name in turn.
    ///
    /// # Errors
    ///
    /// Returns [`IbisError::ModelNotFound`] naming [`Self::reported_name`]
    /// when neither name is in the library.
    pub fn resolve<'a>(&self, models: &'a [Model]) -> Result<&'a Model, IbisError> {
        find(models, &self.preferred)
            .or_else(|| find(models, &self.fallback))
            .ok_or_else(|| IbisError::ModelNotFound(self.reported_name().to_owned()))
    }
}

fn find<'a>(models: &'a [Model], name: &str) -> Option<&'a Model> {
    models.iter().find(|model| model.name == name)
}

/// The comment block the generated netlist opens with.
///
/// Part of Ghidra function `FUN_01bbf630` at `0x01BBF630`.
///
/// The blank line after the banner and the one after the three details are
/// both written, so the header is separated from whatever the template
/// contributes next.
#[must_use]
pub fn header_lines(signal: &str, model: &Model) -> Vec<String> {
    vec![
        GENERATED_BY.to_owned(),
        String::new(),
        format!("* Signal name: {signal}"),
        format!("* Model name: {}", model.name),
        format!("* Model type: {}", model.model_type),
        String::new(),
    ]
}

/// The path the template is expected at.
///
/// Part of Ghidra function `FUN_01bbf630` at `0x01BBF630`.
#[must_use]
pub fn template_path(application_directory: &str) -> String {
    format!("{application_directory}{TEMPLATE_DIRECTORY}{TEMPLATE_FILE}")
}

/// What one conversion needs from the application around it.
pub trait SpiceConversionHost: SeparatorHost {
    /// The directory the SPICE library sits under.
    fn application_directory(&mut self) -> String;

    /// Whether a file exists.
    fn file_exists(&mut self, path: &str) -> bool;

    /// Loads the template's lines.
    fn load_template(&mut self, path: &str) -> Vec<String>;

    /// The model name the named pin refers to, or `None` when the component
    /// has no such pin.
    fn pin_model(&mut self, signal: &str) -> Option<String>;

    /// The models the library holds.
    fn models(&mut self) -> Vec<Model>;

    /// Rewrites a signal name into one a netlist can carry.
    fn sanitise_signal(&mut self, signal: &str) -> String;

    /// Emits the subcircuit body for one model at one corner, given the
    /// template.
    fn emit_body(&mut self, model: &Model, corner: usize, template: &[String]) -> Vec<String>;

    /// Writes the finished netlist.
    fn write(&mut self, path: &str, lines: &[String]);
}

/// Implements Ghidra function `FUN_01bbf630` at `0x01BBF630`.
///
/// Converts one pin of one IBIS component into a SPICE subcircuit file.
///
/// Three things have to be found before anything is written — the template,
/// the pin, and the model — and each missing one abandons the conversion with
/// its own message rather than producing a partial netlist.
///
/// The conversion forces the decimal separator for its whole run, because a
/// netlist written with a comma would be read by SPICE as extra fields rather
/// than refused. The previous separator is put back on every exit, failures
/// included.
///
/// # Errors
///
/// Returns [`IbisError::FileNotFound`] when the template is missing,
/// [`IbisError::PinNotFound`] when the component has no such pin, and
/// [`IbisError::ModelNotFound`] when neither candidate model is in the
/// library.
pub fn convert_pin_to_spice(
    host: &mut impl SpiceConversionHost,
    output_path: &str,
    signal: &str,
    requested_model: Option<&str>,
    corner: usize,
) -> Result<Vec<String>, IbisError> {
    let directory = host.application_directory();
    let template_path = template_path(&directory);

    let guard = DecimalSeparatorGuard::acquire(host);
    convert(
        &mut *guard.host,
        output_path,
        signal,
        requested_model,
        corner,
        &template_path,
    )
}

fn convert(
    host: &mut impl SpiceConversionHost,
    output_path: &str,
    signal: &str,
    requested_model: Option<&str>,
    corner: usize,
    template_path: &str,
) -> Result<Vec<String>, IbisError> {
    if !host.file_exists(template_path) {
        return Err(IbisError::FileNotFound(template_path.to_owned()));
    }
    let template = host.load_template(template_path);

    let Some(pin_model) = host.pin_model(signal) else {
        return Err(IbisError::PinNotFound(signal.to_owned()));
    };

    let sanitised = host.sanitise_signal(signal);
    let lookup = ModelLookup::new(&pin_model, requested_model);
    let models = host.models();
    let model = lookup.resolve(&models)?;

    let mut lines = header_lines(&sanitised, model);
    lines.extend(host.emit_body(model, corner, &template));
    host.write(output_path, &lines);

    Ok(lines)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug, Default)]
    struct Converter {
        separator: char,
        separator_during_body: Option<char>,
        directory: String,
        template_missing: bool,
        pins: Vec<(String, String)>,
        models: Vec<Model>,
        written: Option<(String, Vec<String>)>,
    }

    impl Converter {
        fn ready() -> Self {
            Self {
                separator: ',',
                directory: r"C:\Tina".to_owned(),
                pins: vec![("A1".to_owned(), "OUT".to_owned())],
                models: vec![Model {
                    name: "OUT".to_owned(),
                    model_type: "Output".to_owned(),
                    ..Model::default()
                }],
                ..Self::default()
            }
        }
    }

    impl SeparatorHost for Converter {
        fn decimal_separator(&mut self) -> char {
            self.separator
        }

        fn set_decimal_separator(&mut self, separator: char) {
            self.separator = separator;
        }
    }

    impl SpiceConversionHost for Converter {
        fn application_directory(&mut self) -> String {
            self.directory.clone()
        }

        fn file_exists(&mut self, _path: &str) -> bool {
            !self.template_missing
        }

        fn load_template(&mut self, _path: &str) -> Vec<String> {
            vec![".subckt TEMPLATE".to_owned()]
        }

        fn pin_model(&mut self, signal: &str) -> Option<String> {
            self.pins
                .iter()
                .find(|(pin, _)| pin == signal)
                .map(|(_, model)| model.clone())
        }

        fn models(&mut self) -> Vec<Model> {
            self.models.clone()
        }

        fn sanitise_signal(&mut self, signal: &str) -> String {
            signal.replace(' ', "_")
        }

        fn emit_body(&mut self, model: &Model, corner: usize, template: &[String]) -> Vec<String> {
            self.separator_during_body = Some(self.separator);
            vec![format!(
                "* {} corner {corner} from {} template lines",
                model.name,
                template.len()
            )]
        }

        fn write(&mut self, path: &str, lines: &[String]) {
            self.written = Some((path.to_owned(), lines.to_vec()));
        }
    }

    #[test]
    fn the_template_sits_under_the_spice_library() {
        assert_eq!(
            template_path(r"C:\Tina"),
            r"C:\Tina\SpiceLib\IBIS Models.dat"
        );
    }

    #[test]
    fn the_header_names_the_signal_and_the_model_it_resolved_to() {
        let model = Model {
            name: "OUT".to_owned(),
            model_type: "Output".to_owned(),
            ..Model::default()
        };

        assert_eq!(
            header_lines("A1", &model),
            [
                "* Generated by TINA",
                "",
                "* Signal name: A1",
                "* Model name: OUT",
                "* Model type: Output",
                "",
            ]
        );
    }

    #[test]
    fn the_pins_own_model_is_tried_before_the_one_the_caller_named() {
        let lookup = ModelLookup::new("PIN_MODEL", Some("ASKED_FOR"));
        assert_eq!(lookup.preferred, "PIN_MODEL");
        assert_eq!(lookup.fallback, "ASKED_FOR");

        let models = vec![Model::new("ASKED_FOR"), Model::new("PIN_MODEL")];
        assert_eq!(
            lookup.resolve(&models).expect("one of them is there").name,
            "PIN_MODEL"
        );
    }

    #[test]
    fn the_caller_s_model_rescues_a_pin_whose_own_model_is_missing() {
        let lookup = ModelLookup::new("MISSING", Some("ASKED_FOR"));
        let models = vec![Model::new("ASKED_FOR")];

        assert_eq!(
            lookup
                .resolve(&models)
                .expect("the fall-back is there")
                .name,
            "ASKED_FOR"
        );
    }

    #[test]
    fn naming_nothing_leaves_both_candidates_the_same() {
        let lookup = ModelLookup::new("PIN_MODEL", None);

        assert_eq!(lookup.preferred, lookup.fallback);
        assert_eq!(lookup.reported_name(), "PIN_MODEL");
    }

    #[test]
    fn a_failure_reports_the_name_the_caller_gave() {
        let lookup = ModelLookup::new("PIN_MODEL", Some("ASKED_FOR"));

        assert_eq!(
            lookup.resolve(&[]),
            Err(IbisError::ModelNotFound("ASKED_FOR".to_owned()))
        );
    }

    #[test]
    fn a_conversion_writes_the_header_then_the_body() {
        let mut host = Converter::ready();

        let lines = convert_pin_to_spice(&mut host, "out.cir", "A1", None, 1)
            .expect("everything is present");

        assert_eq!(lines[0], GENERATED_BY);
        assert_eq!(
            lines.last().expect("a body line"),
            "* OUT corner 1 from 1 template lines"
        );
        assert_eq!(host.written.expect("it was written").0, "out.cir");
    }

    #[test]
    fn the_separator_is_forced_while_the_body_is_written_and_put_back_after() {
        let mut host = Converter::ready();

        convert_pin_to_spice(&mut host, "out.cir", "A1", None, 0).expect("it converts");

        assert_eq!(host.separator_during_body, Some(SPICE_DECIMAL_SEPARATOR));
        assert_eq!(host.separator, ',');
    }

    #[test]
    fn a_failed_conversion_still_puts_the_separator_back() {
        let mut host = Converter {
            template_missing: true,
            ..Converter::ready()
        };

        assert!(convert_pin_to_spice(&mut host, "out.cir", "A1", None, 0).is_err());
        assert_eq!(host.separator, ',');
    }

    #[test]
    fn a_missing_template_names_the_path_it_looked_for() {
        let mut host = Converter {
            template_missing: true,
            ..Converter::ready()
        };

        assert_eq!(
            convert_pin_to_spice(&mut host, "out.cir", "A1", None, 0),
            Err(IbisError::FileNotFound(
                r"C:\Tina\SpiceLib\IBIS Models.dat".to_owned()
            ))
        );
    }

    #[test]
    fn a_missing_pin_stops_before_anything_is_written() {
        let mut host = Converter::ready();

        assert_eq!(
            convert_pin_to_spice(&mut host, "out.cir", "NOT_A_PIN", None, 0),
            Err(IbisError::PinNotFound("NOT_A_PIN".to_owned()))
        );
        assert!(host.written.is_none());
    }

    #[test]
    fn a_missing_model_stops_before_anything_is_written() {
        let mut host = Converter {
            models: Vec::new(),
            ..Converter::ready()
        };

        assert_eq!(
            convert_pin_to_spice(&mut host, "out.cir", "A1", None, 0),
            Err(IbisError::ModelNotFound("OUT".to_owned()))
        );
        assert!(host.written.is_none());
    }

    #[test]
    fn the_signal_name_is_sanitised_before_it_reaches_the_header() {
        let mut host = Converter {
            pins: vec![("A 1".to_owned(), "OUT".to_owned())],
            ..Converter::ready()
        };

        let lines = convert_pin_to_spice(&mut host, "out.cir", "A 1", None, 0)
            .expect("everything is present");

        assert!(lines.contains(&"* Signal name: A_1".to_owned()));
    }
}

/// The file the conversion writes into the temporary directory.
pub const IMPORT_OUTPUT_FILE: &str = r"\temp.cir";

/// How an import turned out.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ImportOutcome {
    /// The user chose a pin and the conversion ran.
    Converted {
        /// Where the subcircuit was written.
        output_path: String,
        /// The name the dialog settled on for it.
        name: String,
    },
    /// The user closed the dialog without choosing.
    Cancelled,
}

/// What driving a whole import needs from the application.
pub trait ImportHost: SeparatorHost {
    /// Reads the file into a library. A file that cannot be read abandons the
    /// import.
    ///
    /// # Errors
    ///
    /// Returns whatever the reader reports.
    fn read_library(&mut self, path: &str) -> Result<(), IbisError>;

    /// The directory temporary output is written to, created if it is not
    /// there.
    fn temporary_directory(&mut self) -> String;

    /// Shows the chooser over the library just read, returning what the user
    /// picked.
    fn choose_pin(&mut self) -> Option<ChosenPin>;

    /// Converts the chosen pin into the named file.
    ///
    /// # Errors
    ///
    /// Returns whatever the conversion reports.
    fn convert(&mut self, output_path: &str, chosen: &ChosenPin) -> Result<(), IbisError>;
}

/// What the chooser settled on.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChosenPin {
    /// The signal whose buffer is being imported.
    pub signal: String,
    /// The model to use, when the user named one rather than taking the
    /// pin's own.
    pub model: Option<String>,
    /// The corner the conversion runs at.
    pub corner: usize,
    /// The name the resulting subcircuit is given.
    pub name: String,
}

/// Implements Ghidra function `FUN_01ca4350` at `0x01CA4350`.
///
/// Imports one buffer out of an IBIS file as a SPICE subcircuit.
///
/// This is the whole import in one place: read the file, let the user pick a
/// pin out of it, convert that pin, and hand back where the result went.
///
/// The decimal separator is forced for the *entire* run, not just the
/// conversion — the chooser opens inside the guard too. That matters because
/// the chooser shows numbers from the file, so a comma locale would otherwise
/// display and write them inconsistently within one operation.
///
/// The output always goes to a fixed name in the temporary directory rather
/// than anywhere the user picks, because the caller takes it from there
/// immediately; two imports in a row therefore overwrite one another, which
/// is safe only because nothing keeps the file.
///
/// # Errors
///
/// Returns whatever reading the file or converting the pin reports.
pub fn import_ibis_file(
    host: &mut impl ImportHost,
    path: &str,
) -> Result<ImportOutcome, IbisError> {
    let guard = DecimalSeparatorGuard::acquire(host);
    run_import(&mut *guard.host, path)
}

fn run_import(host: &mut impl ImportHost, path: &str) -> Result<ImportOutcome, IbisError> {
    host.read_library(path)?;

    let output_path = format!("{}{IMPORT_OUTPUT_FILE}", host.temporary_directory());

    let Some(chosen) = host.choose_pin() else {
        return Ok(ImportOutcome::Cancelled);
    };

    host.convert(&output_path, &chosen)?;
    Ok(ImportOutcome::Converted {
        output_path,
        name: chosen.name,
    })
}

#[cfg(test)]
mod import_tests {
    use super::*;

    #[derive(Debug, Default)]
    struct Import {
        separator: char,
        separator_in_chooser: Option<char>,
        read_fails: bool,
        chosen: Option<ChosenPin>,
        converted: Option<String>,
    }

    impl Import {
        fn ready() -> Self {
            Self {
                separator: ',',
                chosen: Some(ChosenPin {
                    signal: "A1".to_owned(),
                    model: None,
                    corner: 0,
                    name: "IBIS_A1".to_owned(),
                }),
                ..Self::default()
            }
        }
    }

    impl SeparatorHost for Import {
        fn decimal_separator(&mut self) -> char {
            self.separator
        }

        fn set_decimal_separator(&mut self, separator: char) {
            self.separator = separator;
        }
    }

    impl ImportHost for Import {
        fn read_library(&mut self, path: &str) -> Result<(), IbisError> {
            if self.read_fails {
                return Err(IbisError::FileNotFound(path.to_owned()));
            }
            Ok(())
        }

        fn temporary_directory(&mut self) -> String {
            r"C:\Temp\Tina".to_owned()
        }

        fn choose_pin(&mut self) -> Option<ChosenPin> {
            self.separator_in_chooser = Some(self.separator);
            self.chosen.clone()
        }

        fn convert(&mut self, output_path: &str, _chosen: &ChosenPin) -> Result<(), IbisError> {
            self.converted = Some(output_path.to_owned());
            Ok(())
        }
    }

    #[test]
    fn an_accepted_import_converts_into_the_temporary_directory() {
        let mut host = Import::ready();

        assert_eq!(
            import_ibis_file(&mut host, "part.ibs"),
            Ok(ImportOutcome::Converted {
                output_path: r"C:\Temp\Tina\temp.cir".to_owned(),
                name: "IBIS_A1".to_owned(),
            })
        );
        assert_eq!(host.converted.as_deref(), Some(r"C:\Temp\Tina\temp.cir"));
    }

    #[test]
    fn the_chooser_runs_inside_the_separator_guard_too() {
        let mut host = Import::ready();
        import_ibis_file(&mut host, "part.ibs").expect("it imports");

        assert_eq!(host.separator_in_chooser, Some(SPICE_DECIMAL_SEPARATOR));
        assert_eq!(host.separator, ',');
    }

    #[test]
    fn cancelling_the_chooser_converts_nothing() {
        let mut host = Import {
            chosen: None,
            ..Import::ready()
        };

        assert_eq!(
            import_ibis_file(&mut host, "part.ibs"),
            Ok(ImportOutcome::Cancelled)
        );
        assert!(host.converted.is_none());
    }

    #[test]
    fn a_file_that_cannot_be_read_never_reaches_the_chooser() {
        let mut host = Import {
            read_fails: true,
            ..Import::ready()
        };

        assert_eq!(
            import_ibis_file(&mut host, "missing.ibs"),
            Err(IbisError::FileNotFound("missing.ibs".to_owned()))
        );
        assert_eq!(host.separator_in_chooser, None);
        assert_eq!(host.separator, ',');
    }

    #[test]
    fn two_imports_write_to_the_same_place() {
        let mut host = Import::ready();
        import_ibis_file(&mut host, "a.ibs").expect("it imports");
        let first = host.converted.clone();
        import_ibis_file(&mut host, "b.ibs").expect("it imports");

        assert_eq!(host.converted, first);
    }
}
