//! Routines built around a single loop.
//!
//! 393 of them. What is recorded is the shape of the loop, what is called inside
//! it and what outside, and whether the body tests anything or reaches for what
//! it calls — which for a routine of this shape is most of what there is.
//!
//! The commonest shape by far is the one that runs its body **before** asking
//! whether to go round again: 197 of the 393. That is worth one caution. A loop
//! written as a count from one number to another, where the compiler could see
//! the count was never nought, comes out of a decompiler in exactly this shape
//! too — so the count here is of the recovered form, and it does not settle how
//! many were written that way. What it does settle is that a reader of the
//! recovered code cannot assume any of these bodies is skipped.

// The addresses are written without separators so the port-mapping importer can
// match them against the recovered functions.
#![allow(clippy::unreadable_literal)]

/// The shape of the loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Loop {
    /// Walks a count from one number to another.
    OverACount,
    /// Runs the body, then asks whether to go round again.
    UntilSomethingHolds,
    /// Asks first, so the body may not run at all.
    WhileSomethingHolds,
}

/// One routine built around a loop.
#[derive(Debug, Clone, Copy)]
pub struct Iterates {
    /// Where it sits.
    pub routine: u32,
    /// The shape of its loop.
    pub shape: Loop,
    /// What it calls inside the loop, in order.
    pub inside: &'static [u32],
    /// What it calls outside it, in order.
    pub outside: &'static [u32],
    /// Whether it reaches for something it calls inside the loop.
    pub reaches_inside: bool,
    /// Whether the body tests anything.
    pub tests_inside: bool,
}

/// Every routine built around a single loop.
pub static ITERATES: [Iterates; 393] = [
    Iterates {
        routine: 0x00408520,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x00409A70],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0040EF50,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x0040EF90],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00410A00,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004109E0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00411000,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00417740, 0x00410CA0],
        outside: &[0x0041D450, 0x00411D60],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00411800,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x0041DD20],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x004122D0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00411E50],
        outside: &[0x00411E50],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00413BE0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00414B90],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00413D30,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00414520],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00414560,
        shape: Loop::OverACount,
        inside: &[0x00414480],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00414590,
        shape: Loop::OverACount,
        inside: &[0x004144D0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x004145C0,
        shape: Loop::OverACount,
        inside: &[0x041B9BBD],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x004154B0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004147F0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00415500,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004147F0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00415EF0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00414930],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00416800,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00414910],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00416830,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00414740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x004169A0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00414840],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00417320,
        shape: Loop::WhileSomethingHolds,
        inside: &[],
        outside: &[0x00414740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0041DD20,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x0041DC50],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0041F230,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x0041F0C0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0041F280,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x0041F190],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0043FB20,
        shape: Loop::WhileSomethingHolds,
        inside: &[],
        outside: &[0x0043F800],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0043FB60,
        shape: Loop::WhileSomethingHolds,
        inside: &[],
        outside: &[0x0043F990],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0043FF00,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0043E6D0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x004479C0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004479A0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0044E140,
        shape: Loop::OverACount,
        inside: &[0x00414AD0, 0x00416CD0],
        outside: &[0x00414480],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0044EDE0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x041D2921, 0x004095F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0044FF90,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x0044FF00, 0x0044B7A0, 0x00417C40, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x004517C0,
        shape: Loop::OverACount,
        inside: &[0x00418590],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00451B70,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004095F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00454E20,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004545B0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x004557C0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00414DE0],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x004589D0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004167A0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x004A0AE0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004A0A40],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x004A0B90,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004A0B20],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x004A4FD0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00594F90],
        outside: &[],
        reaches_inside: true,
        tests_inside: true,
    },
    Iterates {
        routine: 0x004C2420,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004C1D80],
        outside: &[0x00414480],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x004C2810,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004C1D80, 0x004C8440],
        outside: &[0x004C23C0, 0x004C8510, 0x00414480],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x004C2900,
        shape: Loop::OverACount,
        inside: &[0x004BEC10, 0x004C3C80],
        outside: &[0x00419260, 0x004BEC10, 0x004C3C80, 0x00419430],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00527400,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x005273D0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0054C640,
        shape: Loop::OverACount,
        inside: &[0x0053C6C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x005607A0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00417740, 0x00538080],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0058CA60,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00590E20],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00593C30,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00525420],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00593D20,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00525420],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0059B3C0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x005959C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0059B7B0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0059B830],
        outside: &[0x0059B400],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0059B7F0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0059B8C0],
        outside: &[0x0059B400],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x005BF790,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00418590],
        outside: &[0x005C3350],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x005C31B0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x005C2410, 0x005C2810, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x005FBEC0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x005FE090],
        outside: &[0x00412130],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006191E0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x039B8E11, 0x00618E20],
        outside: &[0x00618E50, 0x00618E20, 0x006191B0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0061B3A0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0061A430],
        outside: &[0x00410F20],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00648C90,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x03DE17FB],
        outside: &[0x0065B870],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0064D3E0,
        shape: Loop::OverACount,
        inside: &[0x004113D0, 0x00802770],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00651A30,
        shape: Loop::OverACount,
        inside: &[0x0065BE20],
        outside: &[0x0044D710, 0x004134C0],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x006591F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[0x00659110],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0065B4D0,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x0065B870],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0065CD90,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004DC430, 0x0065CCA0],
        outside: &[0x0065CCA0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0065EC00,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x0064D420],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0065F0A0,
        shape: Loop::OverACount,
        inside: &[0x0065BE20],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x006605F0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00660E20],
        outside: &[0x00660E70],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00660D40,
        shape: Loop::OverACount,
        inside: &[0x006605D0, 0x00660D20, 0x00660D40],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0068D820,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0068BD10],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006A5EA0,
        shape: Loop::OverACount,
        inside: &[0x03A59683],
        outside: &[0x03A59683],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006DD5D0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x006DD3E0],
        outside: &[0x006DD580],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006DD6A0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x006DD5D0],
        outside: &[0x006DD430, 0x006DD390],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006DD870,
        shape: Loop::OverACount,
        inside: &[0x006DD540],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006DF330,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x006DD390],
        outside: &[0x006DDFF0, 0x0065B870, 0x03A2FC9D],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006DFE00,
        shape: Loop::OverACount,
        inside: &[0x006DD0B0, 0x004B89E0],
        outside: &[0x006DECB0, 0x004B89E0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006E0450,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00416AD0],
        outside: &[0x00414480, 0x006DF500, 0x006DDF30, 0x00416AD0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006E23C0,
        shape: Loop::OverACount,
        inside: &[0x006DD3E0, 0x006DD070],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006E2400,
        shape: Loop::OverACount,
        inside: &[0x006DD3E0, 0x006DD090],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006E4F70,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x006E5480],
        outside: &[0x006E2590],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006E5E00,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEBA0, 0x006DD390],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006E8830,
        shape: Loop::OverACount,
        inside: &[0x004170C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006EEA80,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x006EEB10],
        outside: &[0x004B63C0, 0x004AEC30],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006F90E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x006EFCB0, 0x006EF2D0],
        outside: &[0x006EFC30],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x006F92E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x006EFCB0, 0x006EF2D0],
        outside: &[0x006EFC30],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00703D20,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x004B23B0],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00724520,
        shape: Loop::OverACount,
        inside: &[0x00442980],
        outside: &[0x00414480, 0x00416BA0, 0x00416740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00741000,
        shape: Loop::OverACount,
        inside: &[0x00740F30, 0x00423B10],
        outside: &[0x005FD6D0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x007E3780,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x007E2F10],
        outside: &[0x007E2EF0],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x007E40F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x007E34C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x007E4130,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x007E2F10, 0x00410F20],
        outside: &[0x007E2EF0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x007F95C0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x041DE4D6, 0x04154EFC, 0x004095F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x007F9B10,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004113D0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0080CC70,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0080CB10],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0080D190,
        shape: Loop::OverACount,
        inside: &[0x00410AE0, 0x00410AE0, 0x00416DB0],
        outside: &[0x00414560],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0080E110,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00808070, 0x0064FCA0],
        outside: &[0x00808090],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00827890,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x008274C0],
        outside: &[0x00827690],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0082C190,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00410F20],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00836370,
        shape: Loop::OverACount,
        inside: &[0x008324F0],
        outside: &[0x00836330],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0084C100,
        shape: Loop::OverACount,
        inside: &[0x004C06C0, 0x004C1ED0],
        outside: &[0x00414480],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00874240,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x008764D0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x008758E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0043FBA0, 0x00416CD0],
        outside: &[0x0043FBA0, 0x00414480],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x008823E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00879070],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0088F980,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0088F480, 0x0088F480, 0x0088F480],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00896AF0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x0089B8C0, 0x0089B920],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00896B60,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x0089B8C0, 0x0089B920],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x008F8EF0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x008F7250],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x009744D0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00594F90, 0x00410F20, 0x00599670],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x009E0970,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0413E052],
        outside: &[0x0413B16E],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00A05EA0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00A05E80],
        outside: &[0x00A05E80],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00A32EA0,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x00A32E50],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00A37B90,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0062A930, 0x00A37AE0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00A415D0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00A415D0],
        outside: &[0x00410F20],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00A4DDC0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00417C40],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00A529F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00461840],
        outside: &[0x00A53800, 0x00414AD0, 0x00414AD0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00A63B40,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00A62D70],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00A65300,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00416DB0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00A71660,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x00A716A0],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00A94A50,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00A98AC0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00AC1A90],
        outside: &[],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00A990C0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00AC1A90],
        outside: &[],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00A9BE10,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00AC3910],
        outside: &[],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00ABD020,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00AB4030],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00ABF7F0,
        shape: Loop::OverACount,
        inside: &[0x004AEAC0, 0x004113D0],
        outside: &[],
        reaches_inside: true,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00AC5050,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00AC50C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00AD0940,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00AD06F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00AD1400,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00AD13C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00AD1450,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00AD13C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00AD1B30,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00AD1AF0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00AD1B80,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00AD1AF0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00AE3920,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00AD4730],
        outside: &[0x00AD4730],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00B222C0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B22330, 0x00B22280],
        outside: &[0x00B22360],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00B28D50,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B29A30],
        outside: &[0x00B28CF0, 0x00B286F0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00B3FA90,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0040D200, 0x00409A70, 0x00B3F1B0, 0x00409A70],
        outside: &[0x0040D200, 0x00B3F340],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00B437D0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B41F60, 0x00B41BC0],
        outside: &[0x00B41F80],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00B50120,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B4FC70, 0x00B4FC80],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00B53030,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B52D40, 0x00B52D70],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00B53B80,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B53890, 0x00B538C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00B58E40,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B53830, 0x00B506E0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00B58E90,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B52CE0, 0x00B506E0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00B58EE0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B53830, 0x00B50720],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00B58F30,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B52CE0, 0x00B50720],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00B5D1F0,
        shape: Loop::OverACount,
        inside: &[0x00B25710],
        outside: &[0x00B256E0],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00B767A0,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x0040D200, 0x00409A70],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00B909E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x00415020],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00BAD5C0,
        shape: Loop::OverACount,
        inside: &[0x00414DE0],
        outside: &[0x004169F0],
        reaches_inside: true,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00BC5D80,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00BC8990],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00BD1070,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x00410F20, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00BD1750,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00414DE0],
        outside: &[0x004169F0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00BD3BF0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0416F828],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00BD7740,
        shape: Loop::OverACount,
        inside: &[0x00BD7240, 0x00BD7140],
        outside: &[0x004B1E70],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00C1AA50,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00C1AA80],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00C1ABA0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00C21C50,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00C21C50],
        outside: &[0x00410F20],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00C21E10,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00C21D40],
        outside: &[0x00C21AF0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00C2DCD0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00C2DD10,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x004095F0, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00C2EF60,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x004095F0, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00C3C330,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00C3BF30, 0x004AE7E0],
        outside: &[0x01D31720],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00C41560,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00410F20],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00C531C0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B94E60],
        outside: &[],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00C565B0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00C56570],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00C722F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00C71F40],
        outside: &[0x00C72110],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00CE2110,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004113D0, 0x00411550],
        outside: &[0x00411550],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00CF8F40,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00CF8EC0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00D36DC0,
        shape: Loop::OverACount,
        inside: &[0x00D36CF0, 0x04176532],
        outside: &[0x005FD6D0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00D7EC30,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00410F20],
        outside: &[0x00411A80, 0x00410F20, 0x004B1010, 0x00411A00],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00D80FB0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00DAED90,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00DAEC50],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00DAEE70,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x01D347D0, 0x00414FF0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00DAEFD0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00DAEEC0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00DB1E70,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB19A0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00DB1F70,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB1E00],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00DB3430,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB23A0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00DDF340,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0398FB79],
        outside: &[0x0398FB79, 0x0398FB79],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00DFF0D0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00DFEF00],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00E01D50,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004B84C0, 0x00E01B00, 0x004AE7E0],
        outside: &[0x004B84C0],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00E7BFB0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB18C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00E81530,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x004AEAC0, 0x004AEDB0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00E81AE0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AE7E0, 0x00E817C0],
        outside: &[0x004AEF90, 0x00E81B60],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00EAEB60,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00EAE880],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00EBDDB0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0068BD10],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00EBDE10,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0068BD10],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00EF81F0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004095F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00EF83A0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004095F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00EFA3B0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004095F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00EFA3F0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00EF81F0, 0x004095F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F08D50,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x00B89270, 0x00B8E520],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x00F1D0A0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00F1C5C0],
        outside: &[0x01CC5C60],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F20750,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00F1FD70, 0x004AE7E0],
        outside: &[0x01D30F00],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F55790,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00F55390],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F55AD0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00F55390],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F56740,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00F56430],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F59EB0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00F58060],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F74EB0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x00F6F900],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F74F10,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x00F6F910],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F750E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x00F6F910],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F7F3C0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00F7F400],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F7FC60,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B909D0],
        outside: &[0x00409570],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F835C0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0080CC70],
        outside: &[0x00F82A20, 0x00F833F0, 0x00410F20],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F8E8B0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00F8E910,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00FF17F0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00FF1870,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x00FF18F0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01025770,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010257F0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01025870,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010258F0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01025970,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010259F0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01025A70,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01025AF0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01025B70,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01038A30,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01038AB0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01038B30,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01038CB0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01038D30,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01038DB0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01038E30,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0104A030,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0104A0B0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0104A130,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0108C900,
        shape: Loop::OverACount,
        inside: &[0x004AE7E0],
        outside: &[0x00410E60],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0108CE80,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00821790],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0109DCF0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0109DAB0],
        outside: &[0x004B84C0, 0x004B6DC0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010B30A0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x010AF2A0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010B30F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x010AF2D0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010CCD30,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x00C42750],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010D1220,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x00414480],
        reaches_inside: true,
        tests_inside: true,
    },
    Iterates {
        routine: 0x010D18E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x010D3290, 0x010D1930],
        outside: &[0x00B94E60],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x010D3290,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00B94E60],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010D32C0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00B94E60],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010D37D0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00B94E60],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010D3800,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00B94E60],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010DBA60,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00416E20, 0x004170C0],
        outside: &[0x00414610, 0x004170C0, 0x00414AD0, 0x00414480],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x010E44F0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0080CC70],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0112A0F0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0112A080],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0112A150,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0112A0F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0112A1B0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0112A150],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01138FF0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0080CC70],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01153470,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00414AD0, 0x00B0B020, 0x01152760],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01158F80,
        shape: Loop::WhileSomethingHolds,
        inside: &[],
        outside: &[0x01CC5C60],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x011803F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00416BA0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01180450,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00416AD0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0129AC80,
        shape: Loop::OverACount,
        inside: &[0x004170C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x012BF110,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x012BEA40],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0131D470,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x016FD940, 0x0040D200],
        outside: &[0x00414610],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0131FBF0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x016FD940, 0x0040D200],
        outside: &[0x00414610],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0133FED0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x016FD940, 0x0040D200],
        outside: &[0x00414610],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x013415B0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01D347D0, 0x01D34800],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0135A680,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x019AC500],
        outside: &[0x00414480],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01365360,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x004095F0, 0x004AE870],
        outside: &[0x004AEE80],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01368510,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00B95A80, 0x004AEAC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01390530,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x016FD940, 0x0040D200],
        outside: &[0x00414610],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x013ABBA0,
        shape: Loop::OverACount,
        inside: &[0x006DD3E0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x013B2EC0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00B94E60, 0x013B26E0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x013B49F0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00B94E60],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x013B4A50,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B94E60, 0x013B49D0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x013B4BC0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00B94E60],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x013C1D70,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00416AD0],
        outside: &[0x00414480],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x013C1DD0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00416AD0],
        outside: &[0x00414480],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x013D4B80,
        shape: Loop::WhileSomethingHolds,
        inside: &[],
        outside: &[0x01CC5C60],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x013E87B0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0040E200, 0x0040E480, 0x00409900, 0x0040D1C0, 0x00409900],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x013F8520,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0040E200, 0x0040E480, 0x00409900, 0x0040D1C0, 0x00409900],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01444A00,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004095F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01449630,
        shape: Loop::OverACount,
        inside: &[0x01449560],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x014EEB90,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x004179D0, 0x00417C40, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x014FB290,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x014FB230],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x014FB390,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x014FB2E0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x015116C0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0040E200, 0x0040E480, 0x00409900, 0x0040D1C0, 0x00409900],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01544450,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01D347D0, 0x01544410],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01544AE0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01D347D0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01545290,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01D347D0, 0x01544BA0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0156A7E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00416AD0],
        outside: &[0x00414480],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01580FC0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00417740, 0x00410F20],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x015824C0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00410F20, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x015A4190,
        shape: Loop::WhileSomethingHolds,
        inside: &[],
        outside: &[0x015A3240, 0x015A3240, 0x015A2CF0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x015A7530,
        shape: Loop::OverACount,
        inside: &[0x015A74D0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x015ABE50,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x00419BD0, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x015C3360,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x015C2DF0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x015D5660,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x015C2A60, 0x015DEAA0],
        outside: &[0x00417580, 0x015C3360, 0x015DE790, 0x00417740],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x015FA3E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x0040D200],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01600500,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00410F20],
        outside: &[],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01610CC0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00410F20],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01619540,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01619340, 0x01619430, 0x004AE7E0],
        outside: &[0x004B84C0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01619EA0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01619990, 0x01619BA0, 0x004AE7E0],
        outside: &[0x004B84C0, 0x015F46D0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0161AF70,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x004AE7E0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01634C00,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0043F750],
        outside: &[0x00414480],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x016453B0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x01645170],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x016459A0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[0x004AEAC0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01649C10,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x016A96A0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0164A4E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x00419260],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01663140,
        shape: Loop::OverACount,
        inside: &[0x00409A70, 0x0165D6D0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01695AB0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00415020],
        outside: &[0x00415020],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01695B50,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00415020],
        outside: &[0x00415020],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01696DD0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x01696200],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01696E00,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x01696200],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01696E30,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01696200],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01696E60,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01696200],
        outside: &[0x01696200],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x016A3690,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00414FF0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x016B9D80,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x016B9D20],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x016BA340,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00416760, 0x00416AD0, 0x016B9D20],
        outside: &[0x00414480, 0x00414480],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x016BBB50,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00B95CE0, 0x00B95C80],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x016BE360,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x016BADE0, 0x016BDB60],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x016F5480,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x016EA110],
        outside: &[0x016EA110],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x016F54D0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x016EA170],
        outside: &[0x016EA170],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x016F5520,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x01B05110],
        outside: &[0x01B05110],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017057A0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0171AFA0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x0424EFF7],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01743D80,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01743BE0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017C2E00,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x004AE7E0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017C5300,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x017C5250],
        outside: &[0x017C5250, 0x017C5250],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017C54F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x017C5220],
        outside: &[0x017C5220],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017C5530,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x017C52B0],
        outside: &[0x017C52B0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017C5570,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x017C52D0],
        outside: &[0x017C52D0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017C59C0,
        shape: Loop::WhileSomethingHolds,
        inside: &[],
        outside: &[0x0040C2F0, 0x0040AF80],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x017CC990,
        shape: Loop::OverACount,
        inside: &[0x004AEAC0, 0x004AEAC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017CCAE0,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x019954D0],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017E19F0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x013B26E0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017E1A50,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x00B94E60, 0x00B94F10],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017E26C0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x017E1A50],
        outside: &[0x013B4A20],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017E9580,
        shape: Loop::OverACount,
        inside: &[0x013B4BC0, 0x017E8660, 0x013B4860],
        outside: &[0x010D1490, 0x00414480],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017EBB80,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x017EB410],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x017F3480,
        shape: Loop::OverACount,
        inside: &[0x00F835C0, 0x0413EBAB],
        outside: &[0x0413EBAB, 0x0413E052],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x018039A0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x00410F20],
        outside: &[0x00410F20],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01811140,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x00410F20, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0181E370,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x00410F20],
        outside: &[0x00410F20],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0183D140,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0181E3C0, 0x0183D1C0],
        outside: &[0x0181E3E0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x018473D0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x00410F20, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0185ECF0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0185ECD0],
        outside: &[0x0185ECD0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x018769E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x018769C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01879F80,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x00410F20, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0187AFD0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01879FC0, 0x01879960],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0187B020,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01879FC0, 0x01879A00],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01880D80,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x01880030],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0188CFE0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x00410F20, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01899110,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x01899110, 0x00410F20],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x018B80F0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x00410F20, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x018BD020,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x01803A10, 0x018039F0, 0x00410F20],
        outside: &[0x01803BF0, 0x01803A10],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x018C58C0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x00410F20, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x018C6850,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0, 0x004AE870],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x018D68F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x018D6740],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01950600,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004113D0],
        outside: &[0x004113D0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019538A0,
        shape: Loop::OverACount,
        inside: &[0x004113D0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x0197E490,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0197E4F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x0197C1A0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x0197F180,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0197EAA0, 0x0197F350],
        outside: &[0x0197E8B0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019A38E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00410F20],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019A58E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004170C0, 0x00416E20],
        outside: &[0x00414B50, 0x019A5860, 0x00414480],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019A7DF0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x0199E960],
        outside: &[0x0199E960],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019B62C0,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x019B6320],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019B6320,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004095F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019E66B0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB18C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019E6700,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB1E00],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019E7930,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB18C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019E7980,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB1E00],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019E92A0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB18C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019E92F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB1E00],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x019EF000,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x019954D0],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01A0C8B0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00418590],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01A0C8F0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00418590],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01AA1870,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01AA1820],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01AA7760,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x01AA7660],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01AA8F10,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01AA8F70],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01AAA9A0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01AA8F70],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01B0F9A0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00410F20],
        outside: &[0x00411A80, 0x00411A00],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01B110A0,
        shape: Loop::WhileSomethingHolds,
        inside: &[],
        outside: &[0x00409A70],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01B220D0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0, 0x004AE7E0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01B38530,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x00418590],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01B4A8E0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01D347D0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01B4C520,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004095F0],
        outside: &[0x004095F0],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01B719F0,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x00B0B140],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01B71A50,
        shape: Loop::UntilSomethingHolds,
        inside: &[],
        outside: &[0x00B0A890],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01B951F0,
        shape: Loop::OverACount,
        inside: &[0x006DD600, 0x00418590, 0x006DC990],
        outside: &[0x006DED30],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01BE1B80,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01BE0910],
        outside: &[0x00611650],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01BE5380,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01BE52F0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01BFF4D0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01C2DFD0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AE870],
        outside: &[0x004AEE80],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01C65940,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x016FD940, 0x0040D200],
        outside: &[0x00414610],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01C7EB30,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x007E2DA0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01C88AF0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x0080CC70],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01C8D1A0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x007E2F80, 0x007E2DA0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01C98800,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01CAFFE0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01CAFFC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01CC5CC0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01CC5C70],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01CFAC60,
        shape: Loop::OverACount,
        inside: &[],
        outside: &[0x01D3A780],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01D07FE0,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x004AEAC0],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01D0F1C0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01D0F0E0],
        outside: &[0x01D0F160],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01D34C90,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01D34800],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01D3A640,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B94E60, 0x00414480],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01D3A9B0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00B94E60, 0x00414480],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01D3C090,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x01D3C060],
        outside: &[],
        reaches_inside: true,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01D3D700,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00414F50],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01D3D750,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00414F50],
        outside: &[],
        reaches_inside: false,
        tests_inside: true,
    },
    Iterates {
        routine: 0x01D474B0,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x00DB18C0],
        outside: &[],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01D68950,
        shape: Loop::WhileSomethingHolds,
        inside: &[0x017FF620],
        outside: &[0x017FF620],
        reaches_inside: false,
        tests_inside: false,
    },
    Iterates {
        routine: 0x01D74630,
        shape: Loop::UntilSomethingHolds,
        inside: &[0x016EC970],
        outside: &[0x016EB0A0, 0x016EB0A0],
        reaches_inside: false,
        tests_inside: false,
    },
];

/// How many there are.
pub const ITERATES_COUNT: usize = 393;

/// Implements part of the loop family.
///
/// What one routine does, if it is one of these.
#[must_use]
pub fn iterates_at(routine: u32) -> Option<&'static Iterates> {
    ITERATES
        .binary_search_by_key(&routine, |held| held.routine)
        .ok()
        .map(|at| &ITERATES[at])
}

/// Implements part of the loop family.
///
/// Every routine whose loop is of one shape.
#[must_use]
pub fn shaped(shape: Loop) -> Vec<&'static Iterates> {
    ITERATES.iter().filter(|held| held.shape == shape).collect()
}

/// Implements part of the loop family.
///
/// The shapes in use, commonest first.
#[must_use]
pub fn shapes() -> Vec<(Loop, usize)> {
    let mut counted: Vec<(Loop, usize)> = Vec::new();
    for held in &ITERATES {
        match counted.iter_mut().find(|(shape, _)| *shape == held.shape) {
            Some((_, seen)) => *seen += 1,
            None => counted.push((held.shape, 1)),
        }
    }
    counted.sort_by(|left, right| right.1.cmp(&left.1).then(left.0.cmp(&right.0)));
    counted
}

/// Implements part of the loop family.
///
/// The routines whose loop calls nothing.
///
/// The work of the round is done by arithmetic, not by calling out — a walk over
/// something that adds up or copies rather than one that does something to each
/// item.
#[must_use]
pub fn loops_that_call_nothing() -> Vec<&'static Iterates> {
    ITERATES
        .iter()
        .filter(|held| held.inside.is_empty())
        .collect()
}

/// Implements part of the loop family.
///
/// The routines that call nothing outside the loop.
///
/// Everything they do, they do per round. A routine here has no setting up and
/// no finishing off, which is what a plain walk over something looks like.
#[must_use]
pub fn all_the_work_is_in_the_round() -> Vec<&'static Iterates> {
    ITERATES
        .iter()
        .filter(|held| held.outside.is_empty())
        .collect()
}

/// Implements part of the loop family.
///
/// Everything called inside a loop, and how often, commonest first.
#[must_use]
pub fn called_each_round(how_many: usize) -> Vec<(u32, usize)> {
    let mut counted: Vec<(u32, usize)> = Vec::new();
    for call in ITERATES.iter().flat_map(|held| held.inside.iter()) {
        match counted.iter_mut().find(|(at, _)| at == call) {
            Some((_, seen)) => *seen += 1,
            None => counted.push((*call, 1)),
        }
    }
    counted.sort_by(|left, right| right.1.cmp(&left.1).then(left.0.cmp(&right.0)));
    counted.truncate(how_many);
    counted
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_count_is_what_the_table_holds() {
        assert_eq!(ITERATES.len(), ITERATES_COUNT);
    }

    #[test]
    fn the_table_is_sorted_so_it_can_be_searched() {
        assert!(
            ITERATES
                .windows(2)
                .all(|pair| pair[0].routine < pair[1].routine)
        );
    }

    #[test]
    fn a_routine_can_be_found_by_its_address() {
        let known = ITERATES[0].routine;

        assert!(iterates_at(known).is_some());
        assert!(iterates_at(0).is_none());
    }

    #[test]
    fn every_routine_calls_something_somewhere() {
        for held in &ITERATES {
            assert!(
                !held.inside.is_empty() || !held.outside.is_empty(),
                "{:#010X}",
                held.routine
            );
        }
    }

    #[test]
    fn the_commonest_loop_runs_its_body_before_asking_anything() {
        // So a reader cannot assume any of these bodies is skipped.
        assert_eq!(shapes()[0].0, Loop::UntilSomethingHolds);
    }

    #[test]
    fn and_it_is_commoner_than_either_of_the_others() {
        let counted = shapes();

        assert!(counted[0].1 > counted[1].1);
        assert!(counted[0].1 > counted[2].1);
    }

    #[test]
    fn all_three_shapes_are_used() {
        assert_eq!(shapes().len(), 3);
        for (shape, _) in shapes() {
            assert!(!shaped(shape).is_empty(), "{shape:?}");
        }
    }

    #[test]
    fn some_loops_call_nothing_at_all_in_the_round() {
        // The work is arithmetic rather than calling out.
        assert!(!loops_that_call_nothing().is_empty());
    }

    #[test]
    fn and_many_do_nothing_outside_the_round() {
        // No setting up and no finishing off, which is what a plain walk over
        // something looks like.
        let plain = all_the_work_is_in_the_round().len();

        assert!(plain > ITERATES.len() / 4, "{plain} of {}", ITERATES.len());
    }

    #[test]
    fn but_no_routine_is_empty_on_both_counts() {
        for held in &ITERATES {
            assert!(!held.inside.is_empty() || !held.outside.is_empty());
        }
    }

    #[test]
    fn a_minority_test_anything_inside_the_round() {
        let testing = ITERATES.iter().filter(|held| held.tests_inside).count();

        assert!(testing > 0);
        assert!(
            testing * 2 < ITERATES.len(),
            "{testing} of {}",
            ITERATES.len()
        );
    }

    #[test]
    fn fewer_still_reach_for_what_they_call_each_round() {
        let reaching = ITERATES.iter().filter(|held| held.reaches_inside).count();
        let testing = ITERATES.iter().filter(|held| held.tests_inside).count();

        assert!(reaching < testing);
    }

    #[test]
    fn a_few_routines_are_called_by_many_of_these_loops() {
        let busiest = called_each_round(5);

        assert!(busiest[0].1 > 5, "{busiest:?}");
    }

    #[test]
    fn no_loop_body_is_long() {
        for held in &ITERATES {
            assert!(held.inside.len() <= 5, "{:#010X}", held.routine);
            assert!(held.outside.len() <= 5, "{:#010X}", held.routine);
        }
    }

    #[test]
    fn none_of_these_is_already_spoken_for_by_another_sweep() {
        for held in ITERATES.iter().take(200) {
            assert!(crate::straight_line_routines::sequence_of(held.routine).is_none());
            assert!(crate::two_way_routines::choice_at(held.routine).is_none());
            assert!(crate::guarded_routines::guarded_at(held.routine).is_none());
        }
    }

    #[test]
    fn every_routine_is_listed_once() {
        let mut routines: Vec<u32> = ITERATES.iter().map(|held| held.routine).collect();
        let before = routines.len();
        routines.sort_unstable();
        routines.dedup();

        assert_eq!(routines.len(), before);
    }
}
