/* Ghidra address: 008a2b70 */
/* Ghidra symbol: FUN_008a2b70 */


void FUN_008a2b70(longlong *param_1,char param_2)

{
  undefined1 *puVar1;
  char cVar2;
  int iVar3;
  undefined1 auStack_b8 [32];
  undefined8 local_98;
  undefined8 local_90;
  undefined8 local_88;
  undefined8 local_80;
  undefined8 local_78;
  undefined8 local_70;
  undefined8 local_68;
  undefined1 *local_60;
  int local_4c;
  int local_48;
  short *local_40;
  longlong local_38;
  int local_2c;
  undefined8 local_28;
  longlong *local_20;
  
  local_60 = auStack_b8;
  local_90 = 0;
  local_98 = 0;
  local_88 = 0;
  local_78 = 0;
  local_80 = 0;
  local_68 = 0;
  local_70 = 0;
  local_38 = 0;
  local_40 = (short *)0x0;
  puVar1 = auStack_b8;
  if ((param_1 != (longlong *)0x0) &&
     (iVar3 = (**(code **)(*param_1 + 0x28))(param_1), puVar1 = local_60, iVar3 < 1)) {
    (**(code **)(*param_1 + 0x78))(param_1,L".nml=animation/narrative");
    (**(code **)(*param_1 + 0x78))(param_1,L".aac=audio/mp4");
    (**(code **)(*param_1 + 0x78))(param_1,L".aif=audio/x-aiff");
    (**(code **)(*param_1 + 0x78))(param_1,L".aifc=audio/x-aiff");
    (**(code **)(*param_1 + 0x78))(param_1,L".aiff=audio/x-aiff");
    (**(code **)(*param_1 + 0x78))(param_1,L".au=audio/basic");
    (**(code **)(*param_1 + 0x78))(param_1,L".gsm=audio/x-gsm");
    (**(code **)(*param_1 + 0x78))(param_1,L".kar=audio/midi");
    (**(code **)(*param_1 + 0x78))(param_1,L".m3u=audio/mpegurl");
    (**(code **)(*param_1 + 0x78))(param_1,L".m4a=audio/x-mpg");
    (**(code **)(*param_1 + 0x78))(param_1,L".mid=audio/midi");
    (**(code **)(*param_1 + 0x78))(param_1,L".midi=audio/midi");
    (**(code **)(*param_1 + 0x78))(param_1,L".mpega=audio/x-mpg");
    (**(code **)(*param_1 + 0x78))(param_1,L".mp2=audio/x-mpg");
    (**(code **)(*param_1 + 0x78))(param_1,L".mp3=audio/x-mpg");
    (**(code **)(*param_1 + 0x78))(param_1,L".mpga=audio/x-mpg");
    (**(code **)(*param_1 + 0x78))(param_1,L".m3u=audio/x-mpegurl");
    (**(code **)(*param_1 + 0x78))(param_1,L".pls=audio/x-scpls");
    (**(code **)(*param_1 + 0x78))(param_1,L".qcp=audio/vnd.qcelp");
    (**(code **)(*param_1 + 0x78))(param_1,L".ra=audio/x-realaudio");
    (**(code **)(*param_1 + 0x78))(param_1,L".ram=audio/x-pn-realaudio");
    (**(code **)(*param_1 + 0x78))(param_1,L".rm=audio/x-pn-realaudio");
    (**(code **)(*param_1 + 0x78))(param_1,L".sd2=audio/x-sd2");
    (**(code **)(*param_1 + 0x78))(param_1,L".sid=audio/prs.sid");
    (**(code **)(*param_1 + 0x78))(param_1,L".snd=audio/basic");
    (**(code **)(*param_1 + 0x78))(param_1,L".wav=audio/x-wav");
    (**(code **)(*param_1 + 0x78))(param_1,L".wax=audio/x-ms-wax");
    (**(code **)(*param_1 + 0x78))(param_1,L".wma=audio/x-ms-wma");
    (**(code **)(*param_1 + 0x78))(param_1,L".mjf=audio/x-vnd.AudioExplosion.MjuiceMediaFile");
    (**(code **)(*param_1 + 0x78))(param_1,L".art=image/x-jg");
    (**(code **)(*param_1 + 0x78))(param_1,L".bmp=image/bmp");
    (**(code **)(*param_1 + 0x78))(param_1,L".cdr=image/x-coreldraw");
    (**(code **)(*param_1 + 0x78))(param_1,L".cdt=image/x-coreldrawtemplate");
    (**(code **)(*param_1 + 0x78))(param_1,L".cpt=image/x-corelphotopaint");
    (**(code **)(*param_1 + 0x78))(param_1,L".djv=image/vnd.djvu");
    (**(code **)(*param_1 + 0x78))(param_1,L".djvu=image/vnd.djvu");
    (**(code **)(*param_1 + 0x78))(param_1,L".gif=image/gif");
    (**(code **)(*param_1 + 0x78))(param_1,L".ief=image/ief");
    (**(code **)(*param_1 + 0x78))(param_1,L".ico=image/x-icon");
    (**(code **)(*param_1 + 0x78))(param_1,L".jng=image/x-jng");
    (**(code **)(*param_1 + 0x78))(param_1,L".jpg=image/jpeg");
    (**(code **)(*param_1 + 0x78))(param_1,L".jpeg=image/jpeg");
    (**(code **)(*param_1 + 0x78))(param_1,L".jpe=image/jpeg");
    (**(code **)(*param_1 + 0x78))(param_1,L".pat=image/x-coreldrawpattern");
    (**(code **)(*param_1 + 0x78))(param_1,L".pcx=image/pcx");
    (**(code **)(*param_1 + 0x78))(param_1,L".pbm=image/x-portable-bitmap");
    (**(code **)(*param_1 + 0x78))(param_1,L".pgm=image/x-portable-graymap");
    (**(code **)(*param_1 + 0x78))(param_1,L".pict=image/x-pict");
    (**(code **)(*param_1 + 0x78))(param_1,L".png=image/x-png");
    (**(code **)(*param_1 + 0x78))(param_1,L".pnm=image/x-portable-anymap");
    (**(code **)(*param_1 + 0x78))(param_1,L".pntg=image/x-macpaint");
    (**(code **)(*param_1 + 0x78))(param_1,L".ppm=image/x-portable-pixmap");
    (**(code **)(*param_1 + 0x78))(param_1,L".psd=image/x-psd");
    (**(code **)(*param_1 + 0x78))(param_1,L".qtif=image/x-quicktime");
    (**(code **)(*param_1 + 0x78))(param_1,L".ras=image/x-cmu-raster");
    (**(code **)(*param_1 + 0x78))(param_1,L".rf=image/vnd.rn-realflash");
    (**(code **)(*param_1 + 0x78))(param_1,L".rgb=image/x-rgb");
    (**(code **)(*param_1 + 0x78))(param_1,L".rp=image/vnd.rn-realpix");
    (**(code **)(*param_1 + 0x78))(param_1,L".sgi=image/x-sgi");
    (**(code **)(*param_1 + 0x78))(param_1,L".svg=image/svg+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".svgz=image/svg+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".targa=image/x-targa");
    (**(code **)(*param_1 + 0x78))(param_1,L".tif=image/x-tiff");
    (**(code **)(*param_1 + 0x78))(param_1,L".wbmp=image/vnd.wap.wbmp");
    (**(code **)(*param_1 + 0x78))(param_1,L".webp=image/webp");
    (**(code **)(*param_1 + 0x78))(param_1,L".xbm=image/xbm");
    (**(code **)(*param_1 + 0x78))(param_1,L".xbm=image/x-xbitmap");
    (**(code **)(*param_1 + 0x78))(param_1,L".xpm=image/x-xpixmap");
    (**(code **)(*param_1 + 0x78))(param_1,L".xwd=image/x-xwindowdump");
    (**(code **)(*param_1 + 0x78))(param_1,L".323=text/h323");
    (**(code **)(*param_1 + 0x78))(param_1,L".xml=text/xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".uls=text/iuls");
    (**(code **)(*param_1 + 0x78))(param_1,L".txt=text/plain");
    (**(code **)(*param_1 + 0x78))(param_1,L".rtx=text/richtext");
    (**(code **)(*param_1 + 0x78))(param_1,L".wsc=text/scriptlet");
    (**(code **)(*param_1 + 0x78))(param_1,L".rt=text/vnd.rn-realtext");
    (**(code **)(*param_1 + 0x78))(param_1,L".htt=text/webviewhtml");
    (**(code **)(*param_1 + 0x78))(param_1,L".htc=text/x-component");
    (**(code **)(*param_1 + 0x78))(param_1,L".vcf=text/x-vcard");
    (**(code **)(*param_1 + 0x78))(param_1,L".asf=video/x-ms-asf");
    (**(code **)(*param_1 + 0x78))(param_1,L".asx=video/x-ms-asf");
    (**(code **)(*param_1 + 0x78))(param_1,L".avi=video/x-msvideo");
    (**(code **)(*param_1 + 0x78))(param_1,L".dl=video/dl");
    (**(code **)(*param_1 + 0x78))(param_1,L".dv=video/dv");
    (**(code **)(*param_1 + 0x78))(param_1,L".flc=video/flc");
    (**(code **)(*param_1 + 0x78))(param_1,L".fli=video/fli");
    (**(code **)(*param_1 + 0x78))(param_1,L".gl=video/gl");
    (**(code **)(*param_1 + 0x78))(param_1,L".lsf=video/x-la-asf");
    (**(code **)(*param_1 + 0x78))(param_1,L".lsx=video/x-la-asf");
    (**(code **)(*param_1 + 0x78))(param_1,L".mng=video/x-mng");
    (**(code **)(*param_1 + 0x78))(param_1,L".mp2=video/mpeg");
    (**(code **)(*param_1 + 0x78))(param_1,L".mp3=video/mpeg");
    (**(code **)(*param_1 + 0x78))(param_1,L".mp4=video/mpeg");
    (**(code **)(*param_1 + 0x78))(param_1,L".mpeg=video/x-mpeg2a");
    (**(code **)(*param_1 + 0x78))(param_1,L".mpa=video/mpeg");
    (**(code **)(*param_1 + 0x78))(param_1,L".mpe=video/mpeg");
    (**(code **)(*param_1 + 0x78))(param_1,L".mpg=video/mpeg");
    (**(code **)(*param_1 + 0x78))(param_1,L".ogv=video/ogg");
    (**(code **)(*param_1 + 0x78))(param_1,L".moov=video/quicktime");
    (**(code **)(*param_1 + 0x78))(param_1,L".mov=video/quicktime");
    (**(code **)(*param_1 + 0x78))(param_1,L".mxu=video/vnd.mpegurl");
    (**(code **)(*param_1 + 0x78))(param_1,L".qt=video/quicktime");
    (**(code **)(*param_1 + 0x78))(param_1,L".qtc=video/x-qtc");
    (**(code **)(*param_1 + 0x78))(param_1,L".rv=video/vnd.rn-realvideo");
    (**(code **)(*param_1 + 0x78))(param_1,L".ivf=video/x-ivf");
    (**(code **)(*param_1 + 0x78))(param_1,L".webm=video/webm");
    (**(code **)(*param_1 + 0x78))(param_1,L".wm=video/x-ms-wm");
    (**(code **)(*param_1 + 0x78))(param_1,L".wmp=video/x-ms-wmp");
    (**(code **)(*param_1 + 0x78))(param_1,L".wmv=video/x-ms-wmv");
    (**(code **)(*param_1 + 0x78))(param_1,L".wmx=video/x-ms-wmx");
    (**(code **)(*param_1 + 0x78))(param_1,L".wvx=video/x-ms-wvx");
    (**(code **)(*param_1 + 0x78))(param_1,L".rms=video/vnd.rn-realvideo-secure");
    (**(code **)(*param_1 + 0x78))(param_1,L".asx=video/x-ms-asf-plugin");
    (**(code **)(*param_1 + 0x78))(param_1,L".movie=video/x-sgi-movie");
    (**(code **)(*param_1 + 0x78))(param_1,L".7z=application/x-7z-compressed");
    (**(code **)(*param_1 + 0x78))(param_1,L".a=application/x-archive");
    (**(code **)(*param_1 + 0x78))(param_1,L".aab=application/x-authorware-bin");
    (**(code **)(*param_1 + 0x78))(param_1,L".aam=application/x-authorware-map");
    (**(code **)(*param_1 + 0x78))(param_1,L".aas=application/x-authorware-seg");
    (**(code **)(*param_1 + 0x78))(param_1,L".abw=application/x-abiword");
    (**(code **)(*param_1 + 0x78))(param_1,L".ace=application/x-ace-compressed");
    (**(code **)(*param_1 + 0x78))(param_1,L".ai=application/postscript");
    (**(code **)(*param_1 + 0x78))(param_1,L".alz=application/x-alz-compressed");
    (**(code **)(*param_1 + 0x78))(param_1,L".ani=application/x-navi-animation");
    (**(code **)(*param_1 + 0x78))(param_1,L".arj=application/x-arj");
    (**(code **)(*param_1 + 0x78))(param_1,L".asf=application/vnd.ms-asf");
    (**(code **)(*param_1 + 0x78))(param_1,L".bat=application/x-msdos-program");
    (**(code **)(*param_1 + 0x78))(param_1,L".bcpio=application/x-bcpio");
    (**(code **)(*param_1 + 0x78))(param_1,L".boz=application/x-bzip2");
    (**(code **)(*param_1 + 0x78))(param_1,L".bz=application/x-bzip");
    (**(code **)(*param_1 + 0x78))(param_1,L".bz2=application/x-bzip2");
    (**(code **)(*param_1 + 0x78))(param_1,L".cab=application/vnd.ms-cab-compressed");
    (**(code **)(*param_1 + 0x78))(param_1,L".cat=application/vnd.ms-pki.seccat");
    (**(code **)(*param_1 + 0x78))(param_1,L".ccn=application/x-cnc");
    (**(code **)(*param_1 + 0x78))(param_1,L".cco=application/x-cocoa");
    (**(code **)(*param_1 + 0x78))(param_1,L".cdf=application/x-cdf");
    (**(code **)(*param_1 + 0x78))(param_1,L".cer=application/x-x509-ca-cert");
    (**(code **)(*param_1 + 0x78))(param_1,L".chm=application/vnd.ms-htmlhelp");
    (**(code **)(*param_1 + 0x78))(param_1,L".chrt=application/vnd.kde.kchart");
    (**(code **)(*param_1 + 0x78))(param_1,L".cil=application/vnd.ms-artgalry");
    (**(code **)(*param_1 + 0x78))(param_1,L".class=application/java-vm");
    (**(code **)(*param_1 + 0x78))(param_1,L".com=application/x-msdos-program");
    (**(code **)(*param_1 + 0x78))(param_1,L".clp=application/x-msclip");
    (**(code **)(*param_1 + 0x78))(param_1,L".cpio=application/x-cpio");
    (**(code **)(*param_1 + 0x78))(param_1,L".cpt=application/mac-compactpro");
    (**(code **)(*param_1 + 0x78))(param_1,L".cqk=application/x-calquick");
    (**(code **)(*param_1 + 0x78))(param_1,L".crd=application/x-mscardfile");
    (**(code **)(*param_1 + 0x78))(param_1,L".crl=application/pkix-crl");
    (**(code **)(*param_1 + 0x78))(param_1,L".csh=application/x-csh");
    (**(code **)(*param_1 + 0x78))(param_1,L".dar=application/x-dar");
    (**(code **)(*param_1 + 0x78))(param_1,L".dbf=application/x-dbase");
    (**(code **)(*param_1 + 0x78))(param_1,L".dcr=application/x-director");
    (**(code **)(*param_1 + 0x78))(param_1,L".deb=application/x-debian-package");
    (**(code **)(*param_1 + 0x78))(param_1,L".dir=application/x-director");
    (**(code **)(*param_1 + 0x78))(param_1,L".dist=vnd.apple.installer+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".distz=vnd.apple.installer+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".dll=application/x-msdos-program");
    (**(code **)(*param_1 + 0x78))(param_1,L".dmg=application/x-apple-diskimage");
    (**(code **)(*param_1 + 0x78))(param_1,L".doc=application/msword");
    (**(code **)(*param_1 + 0x78))(param_1,L".dot=application/msword");
    (**(code **)(*param_1 + 0x78))(param_1,L".dvi=application/x-dvi");
    (**(code **)(*param_1 + 0x78))(param_1,L".dxr=application/x-director");
    (**(code **)(*param_1 + 0x78))(param_1,L".ebk=application/x-expandedbook");
    (**(code **)(*param_1 + 0x78))(param_1,L".eps=application/postscript");
    (**(code **)(*param_1 + 0x78))(param_1,L".evy=application/envoy");
    (**(code **)(*param_1 + 0x78))(param_1,L".exe=application/x-msdos-program");
    (**(code **)(*param_1 + 0x78))(param_1,L".fdf=application/vnd.fdf");
    (**(code **)(*param_1 + 0x78))(param_1,L".fif=application/fractals");
    (**(code **)(*param_1 + 0x78))(param_1,L".flm=application/vnd.kde.kivio");
    (**(code **)(*param_1 + 0x78))(param_1,L".fml=application/x-file-mirror-list");
    (**(code **)(*param_1 + 0x78))(param_1,L".gzip=application/x-gzip");
    (**(code **)(*param_1 + 0x78))(param_1,L".gnumeric=application/x-gnumeric");
    (**(code **)(*param_1 + 0x78))(param_1,L".gtar=application/x-gtar");
    (**(code **)(*param_1 + 0x78))(param_1,L".gz=application/x-gzip");
    (**(code **)(*param_1 + 0x78))(param_1,L".hdf=application/x-hdf");
    (**(code **)(*param_1 + 0x78))(param_1,L".hlp=application/winhlp");
    (**(code **)(*param_1 + 0x78))(param_1,L".hpf=application/x-icq-hpf");
    (**(code **)(*param_1 + 0x78))(param_1,L".hqx=application/mac-binhex40");
    (**(code **)(*param_1 + 0x78))(param_1,L".hta=application/hta");
    (**(code **)(*param_1 + 0x78))(param_1,L".ims=application/vnd.ms-ims");
    (**(code **)(*param_1 + 0x78))(param_1,L".ins=application/x-internet-signup");
    (**(code **)(*param_1 + 0x78))(param_1,L".iii=application/x-iphone");
    (**(code **)(*param_1 + 0x78))(param_1,L".iso=application/x-iso9660-image");
    (**(code **)(*param_1 + 0x78))(param_1,L".jar=application/java-archive");
    (**(code **)(*param_1 + 0x78))(param_1,L".karbon=application/vnd.kde.karbon");
    (**(code **)(*param_1 + 0x78))(param_1,L".kfo=application/vnd.kde.kformula");
    (**(code **)(*param_1 + 0x78))(param_1,L".kon=application/vnd.kde.kontour");
    (**(code **)(*param_1 + 0x78))(param_1,L".kpr=application/vnd.kde.kpresenter");
    (**(code **)(*param_1 + 0x78))(param_1,L".kpt=application/vnd.kde.kpresenter");
    (**(code **)(*param_1 + 0x78))(param_1,L".kwd=application/vnd.kde.kword");
    (**(code **)(*param_1 + 0x78))(param_1,L".kwt=application/vnd.kde.kword");
    (**(code **)(*param_1 + 0x78))(param_1,L".latex=application/x-latex");
    (**(code **)(*param_1 + 0x78))(param_1,L".lha=application/x-lzh");
    (**(code **)(*param_1 + 0x78))(param_1,L".lcc=application/fastman");
    (**(code **)(*param_1 + 0x78))(param_1,L".lrm=application/vnd.ms-lrm");
    (**(code **)(*param_1 + 0x78))(param_1,L".lz=application/x-lzip");
    (**(code **)(*param_1 + 0x78))(param_1,L".lzh=application/x-lzh");
    (**(code **)(*param_1 + 0x78))(param_1,L".lzma=application/x-lzma");
    (**(code **)(*param_1 + 0x78))(param_1,L".lzo=application/x-lzop");
    (**(code **)(*param_1 + 0x78))(param_1,L".lzx=application/x-lzx");
    (**(code **)(*param_1 + 0x78))(param_1,L".m13=application/x-msmediaview");
    (**(code **)(*param_1 + 0x78))(param_1,L".m14=application/x-msmediaview");
    (**(code **)(*param_1 + 0x78))(param_1,L".mpp=application/vnd.ms-project");
    (**(code **)(*param_1 + 0x78))(param_1,L".mvb=application/x-msmediaview");
    (**(code **)(*param_1 + 0x78))(param_1,L".man=application/x-troff-man");
    (**(code **)(*param_1 + 0x78))(param_1,L".mdb=application/x-msaccess");
    (**(code **)(*param_1 + 0x78))(param_1,L".me=application/x-troff-me");
    (**(code **)(*param_1 + 0x78))(param_1,L".ms=application/x-troff-ms");
    (**(code **)(*param_1 + 0x78))(param_1,L".msi=application/x-msi");
    (**(code **)(*param_1 + 0x78))(param_1,L".mpkg=vnd.apple.installer+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".mny=application/x-msmoney");
    (**(code **)(*param_1 + 0x78))(param_1,L".nix=application/x-mix-transfer");
    (**(code **)(*param_1 + 0x78))(param_1,L".o=application/x-object");
    (**(code **)(*param_1 + 0x78))(param_1,L".oda=application/oda");
    (**(code **)(*param_1 + 0x78))(param_1,L".odb=application/vnd.oasis.opendocument.database");
    (**(code **)(*param_1 + 0x78))(param_1,L".odc=application/vnd.oasis.opendocument.chart");
    (**(code **)(*param_1 + 0x78))(param_1,L".odf=application/vnd.oasis.opendocument.formula");
    (**(code **)(*param_1 + 0x78))(param_1,L".odg=application/vnd.oasis.opendocument.graphics");
    (**(code **)(*param_1 + 0x78))(param_1,L".odi=application/vnd.oasis.opendocument.image");
    (**(code **)(*param_1 + 0x78))(param_1,L".odm=application/vnd.oasis.opendocument.text-master");
    (**(code **)(*param_1 + 0x78))(param_1,L".odp=application/vnd.oasis.opendocument.presentation");
    (**(code **)(*param_1 + 0x78))(param_1,L".ods=application/vnd.oasis.opendocument.spreadsheet");
    (**(code **)(*param_1 + 0x78))(param_1,L".ogg=application/ogg");
    (**(code **)(*param_1 + 0x78))(param_1,L".odt=application/vnd.oasis.opendocument.text");
    (**(code **)(*param_1 + 0x78))
              (param_1,L".otg=application/vnd.oasis.opendocument.graphics-template");
    (**(code **)(*param_1 + 0x78))(param_1,L".oth=application/vnd.oasis.opendocument.text-web");
    (**(code **)(*param_1 + 0x78))
              (param_1,L".otp=application/vnd.oasis.opendocument.presentation-template");
    (**(code **)(*param_1 + 0x78))
              (param_1,L".ots=application/vnd.oasis.opendocument.spreadsheet-template");
    (**(code **)(*param_1 + 0x78))(param_1,L".ott=application/vnd.oasis.opendocument.text-template")
    ;
    (**(code **)(*param_1 + 0x78))(param_1,L".p10=application/pkcs10");
    (**(code **)(*param_1 + 0x78))(param_1,L".p12=application/x-pkcs12");
    (**(code **)(*param_1 + 0x78))(param_1,L".p7b=application/x-pkcs7-certificates");
    (**(code **)(*param_1 + 0x78))(param_1,L".p7m=application/pkcs7-mime");
    (**(code **)(*param_1 + 0x78))(param_1,L".p7r=application/x-pkcs7-certreqresp");
    (**(code **)(*param_1 + 0x78))(param_1,L".p7s=application/pkcs7-signature");
    (**(code **)(*param_1 + 0x78))(param_1,L".package=application/vnd.autopackage");
    (**(code **)(*param_1 + 0x78))(param_1,L".pfr=application/font-tdpfr");
    (**(code **)(*param_1 + 0x78))(param_1,L".pkg=vnd.apple.installer+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".pdf=application/pdf");
    (**(code **)(*param_1 + 0x78))(param_1,L".pko=application/vnd.ms-pki.pko");
    (**(code **)(*param_1 + 0x78))(param_1,L".pl=application/x-perl");
    (**(code **)(*param_1 + 0x78))(param_1,L".pnq=application/x-icq-pnq");
    (**(code **)(*param_1 + 0x78))(param_1,L".pot=application/mspowerpoint");
    (**(code **)(*param_1 + 0x78))(param_1,L".pps=application/mspowerpoint");
    (**(code **)(*param_1 + 0x78))(param_1,L".ppt=application/mspowerpoint");
    (**(code **)(*param_1 + 0x78))(param_1,L".ppz=application/mspowerpoint");
    (**(code **)(*param_1 + 0x78))(param_1,L".ps=application/postscript");
    (**(code **)(*param_1 + 0x78))(param_1,L".pub=application/x-mspublisher");
    (**(code **)(*param_1 + 0x78))(param_1,L".qpw=application/x-quattropro");
    (**(code **)(*param_1 + 0x78))(param_1,L".qtl=application/x-quicktimeplayer");
    (**(code **)(*param_1 + 0x78))(param_1,L".rar=application/rar");
    (**(code **)(*param_1 + 0x78))(param_1,L".rdf=application/rdf+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".rjs=application/vnd.rn-realsystem-rjs");
    (**(code **)(*param_1 + 0x78))(param_1,L".rm=application/vnd.rn-realmedia");
    (**(code **)(*param_1 + 0x78))(param_1,L".rmf=application/vnd.rmf");
    (**(code **)(*param_1 + 0x78))(param_1,L".rmp=application/vnd.rn-rn_music_package");
    (**(code **)(*param_1 + 0x78))(param_1,L".rmx=application/vnd.rn-realsystem-rmx");
    (**(code **)(*param_1 + 0x78))(param_1,L".rnx=application/vnd.rn-realplayer");
    (**(code **)(*param_1 + 0x78))(param_1,L".rpm=application/x-redhat-package-manager");
    (**(code **)(*param_1 + 0x78))(param_1,L".rsml=application/vnd.rn-rsml");
    (**(code **)(*param_1 + 0x78))(param_1,L".rtsp=application/x-rtsp");
    (**(code **)(*param_1 + 0x78))(param_1,L".rss=application/rss+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".scm=application/x-icq-scm");
    (**(code **)(*param_1 + 0x78))(param_1,L".ser=application/java-serialized-object");
    (**(code **)(*param_1 + 0x78))(param_1,L".scd=application/x-msschedule");
    (**(code **)(*param_1 + 0x78))(param_1,L".sda=application/vnd.stardivision.draw");
    (**(code **)(*param_1 + 0x78))(param_1,L".sdc=application/vnd.stardivision.calc");
    (**(code **)(*param_1 + 0x78))(param_1,L".sdd=application/vnd.stardivision.impress");
    (**(code **)(*param_1 + 0x78))(param_1,L".sdp=application/x-sdp");
    (**(code **)(*param_1 + 0x78))(param_1,L".setpay=application/set-payment-initiation");
    (**(code **)(*param_1 + 0x78))(param_1,L".setreg=application/set-registration-initiation");
    (**(code **)(*param_1 + 0x78))(param_1,L".sh=application/x-sh");
    (**(code **)(*param_1 + 0x78))(param_1,L".shar=application/x-shar");
    (**(code **)(*param_1 + 0x78))(param_1,L".shw=application/presentations");
    (**(code **)(*param_1 + 0x78))(param_1,L".sit=application/x-stuffit");
    (**(code **)(*param_1 + 0x78))(param_1,L".sitx=application/x-stuffitx");
    (**(code **)(*param_1 + 0x78))(param_1,L".skd=application/x-koan");
    (**(code **)(*param_1 + 0x78))(param_1,L".skm=application/x-koan");
    (**(code **)(*param_1 + 0x78))(param_1,L".skp=application/x-koan");
    (**(code **)(*param_1 + 0x78))(param_1,L".skt=application/x-koan");
    (**(code **)(*param_1 + 0x78))(param_1,L".smf=application/vnd.stardivision.math");
    (**(code **)(*param_1 + 0x78))(param_1,L".smi=application/smil");
    (**(code **)(*param_1 + 0x78))(param_1,L".smil=application/smil");
    (**(code **)(*param_1 + 0x78))(param_1,L".spl=application/futuresplash");
    (**(code **)(*param_1 + 0x78))(param_1,L".ssm=application/streamingmedia");
    (**(code **)(*param_1 + 0x78))(param_1,L".sst=application/vnd.ms-pki.certstore");
    (**(code **)(*param_1 + 0x78))(param_1,L".stc=application/vnd.sun.xml.calc.template");
    (**(code **)(*param_1 + 0x78))(param_1,L".std=application/vnd.sun.xml.draw.template");
    (**(code **)(*param_1 + 0x78))(param_1,L".sti=application/vnd.sun.xml.impress.template");
    (**(code **)(*param_1 + 0x78))(param_1,L".stl=application/vnd.ms-pki.stl");
    (**(code **)(*param_1 + 0x78))(param_1,L".stw=application/vnd.sun.xml.writer.template");
    (**(code **)(*param_1 + 0x78))(param_1,L".svi=application/softvision");
    (**(code **)(*param_1 + 0x78))(param_1,L".sv4cpio=application/x-sv4cpio");
    (**(code **)(*param_1 + 0x78))(param_1,L".sv4crc=application/x-sv4crc");
    (**(code **)(*param_1 + 0x78))(param_1,L".swf=application/x-shockwave-flash");
    (**(code **)(*param_1 + 0x78))(param_1,L".swf1=application/x-shockwave-flash");
    (**(code **)(*param_1 + 0x78))(param_1,L".sxc=application/vnd.sun.xml.calc");
    (**(code **)(*param_1 + 0x78))(param_1,L".sxi=application/vnd.sun.xml.impress");
    (**(code **)(*param_1 + 0x78))(param_1,L".sxm=application/vnd.sun.xml.math");
    (**(code **)(*param_1 + 0x78))(param_1,L".sxw=application/vnd.sun.xml.writer");
    (**(code **)(*param_1 + 0x78))(param_1,L".sxg=application/vnd.sun.xml.writer.global");
    (**(code **)(*param_1 + 0x78))(param_1,L".t=application/x-troff");
    (**(code **)(*param_1 + 0x78))(param_1,L".tar=application/x-tar");
    (**(code **)(*param_1 + 0x78))(param_1,L".tcl=application/x-tcl");
    (**(code **)(*param_1 + 0x78))(param_1,L".tex=application/x-tex");
    (**(code **)(*param_1 + 0x78))(param_1,L".texi=application/x-texinfo");
    (**(code **)(*param_1 + 0x78))(param_1,L".texinfo=application/x-texinfo");
    (**(code **)(*param_1 + 0x78))(param_1,L".tbz=application/x-bzip-compressed-tar");
    (**(code **)(*param_1 + 0x78))(param_1,L".tbz2=application/x-bzip-compressed-tar");
    (**(code **)(*param_1 + 0x78))(param_1,L".tgz=application/x-compressed-tar");
    (**(code **)(*param_1 + 0x78))(param_1,L".tlz=application/x-lzma-compressed-tar");
    (**(code **)(*param_1 + 0x78))(param_1,L".tr=application/x-troff");
    (**(code **)(*param_1 + 0x78))(param_1,L".trm=application/x-msterminal");
    (**(code **)(*param_1 + 0x78))(param_1,L".troff=application/x-troff");
    (**(code **)(*param_1 + 0x78))(param_1,L".tsp=application/dsptype");
    (**(code **)(*param_1 + 0x78))(param_1,L".torrent=application/x-bittorrent");
    (**(code **)(*param_1 + 0x78))(param_1,L".ttz=application/t-time");
    (**(code **)(*param_1 + 0x78))(param_1,L".txz=application/x-xz-compressed-tar");
    (**(code **)(*param_1 + 0x78))(param_1,L".udeb=application/x-debian-package");
    (**(code **)(*param_1 + 0x78))(param_1,L".uin=application/x-icq");
    (**(code **)(*param_1 + 0x78))(param_1,L".urls=application/x-url-list");
    (**(code **)(*param_1 + 0x78))(param_1,L".ustar=application/x-ustar");
    (**(code **)(*param_1 + 0x78))(param_1,L".vcd=application/x-cdlink");
    (**(code **)(*param_1 + 0x78))(param_1,L".vor=application/vnd.stardivision.writer");
    (**(code **)(*param_1 + 0x78))(param_1,L".vsl=application/x-cnet-vsl");
    (**(code **)(*param_1 + 0x78))(param_1,L".wcm=application/vnd.ms-works");
    (**(code **)(*param_1 + 0x78))(param_1,L".wb1=application/x-quattropro");
    (**(code **)(*param_1 + 0x78))(param_1,L".wb2=application/x-quattropro");
    (**(code **)(*param_1 + 0x78))(param_1,L".wb3=application/x-quattropro");
    (**(code **)(*param_1 + 0x78))(param_1,L".wdb=application/vnd.ms-works");
    (**(code **)(*param_1 + 0x78))(param_1,L".wks=application/vnd.ms-works");
    (**(code **)(*param_1 + 0x78))(param_1,L".wmd=application/x-ms-wmd");
    (**(code **)(*param_1 + 0x78))(param_1,L".wms=application/x-ms-wms");
    (**(code **)(*param_1 + 0x78))(param_1,L".wmz=application/x-ms-wmz");
    (**(code **)(*param_1 + 0x78))(param_1,L".wp5=application/wordperfect5.1");
    (**(code **)(*param_1 + 0x78))(param_1,L".wpd=application/wordperfect");
    (**(code **)(*param_1 + 0x78))(param_1,L".wpl=application/vnd.ms-wpl");
    (**(code **)(*param_1 + 0x78))(param_1,L".wps=application/vnd.ms-works");
    (**(code **)(*param_1 + 0x78))(param_1,L".wri=application/x-mswrite");
    (**(code **)(*param_1 + 0x78))(param_1,L".xfdf=application/vnd.adobe.xfdf");
    (**(code **)(*param_1 + 0x78))(param_1,L".xls=application/x-msexcel");
    (**(code **)(*param_1 + 0x78))(param_1,L".xlb=application/x-msexcel");
    (**(code **)(*param_1 + 0x78))(param_1,L".xpi=application/x-xpinstall");
    (**(code **)(*param_1 + 0x78))(param_1,L".xps=application/vnd.ms-xpsdocument");
    (**(code **)(*param_1 + 0x78))(param_1,L".xsd=application/vnd.sun.xml.draw");
    (**(code **)(*param_1 + 0x78))(param_1,L".xul=application/vnd.mozilla.xul+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".z=application/x-compress");
    (**(code **)(*param_1 + 0x78))(param_1,L".zoo=application/x-zoo");
    (**(code **)(*param_1 + 0x78))(param_1,L".zip=application/x-zip-compressed");
    (**(code **)(*param_1 + 0x78))(param_1,L".wbmp=image/vnd.wap.wbmp");
    (**(code **)(*param_1 + 0x78))(param_1,L".wml=text/vnd.wap.wml");
    (**(code **)(*param_1 + 0x78))(param_1,L".wmlc=application/vnd.wap.wmlc");
    (**(code **)(*param_1 + 0x78))(param_1,L".wmls=text/vnd.wap.wmlscript");
    (**(code **)(*param_1 + 0x78))(param_1,L".wmlsc=application/vnd.wap.wmlscriptc");
    (**(code **)(*param_1 + 0x78))(param_1,L".asm=text/x-asm");
    (**(code **)(*param_1 + 0x78))(param_1,L".p=text/x-pascal");
    (**(code **)(*param_1 + 0x78))(param_1,L".pas=text/x-pascal");
    (**(code **)(*param_1 + 0x78))(param_1,L".cs=text/x-csharp");
    (**(code **)(*param_1 + 0x78))(param_1,L".c=text/x-csrc");
    (**(code **)(*param_1 + 0x78))(param_1,L".c++=text/x-c++src");
    (**(code **)(*param_1 + 0x78))(param_1,L".cpp=text/x-c++src");
    (**(code **)(*param_1 + 0x78))(param_1,L".cxx=text/x-c++src");
    (**(code **)(*param_1 + 0x78))(param_1,L".cc=text/x-c++src");
    (**(code **)(*param_1 + 0x78))(param_1,L".h=text/x-chdr");
    (**(code **)(*param_1 + 0x78))(param_1,L".h++=text/x-c++hdr");
    (**(code **)(*param_1 + 0x78))(param_1,L".hpp=text/x-c++hdr");
    (**(code **)(*param_1 + 0x78))(param_1,L".hxx=text/x-c++hdr");
    (**(code **)(*param_1 + 0x78))(param_1,L".hh=text/x-c++hdr");
    (**(code **)(*param_1 + 0x78))(param_1,L".java=text/x-java");
    (**(code **)(*param_1 + 0x78))(param_1,L".css=text/css");
    (**(code **)(*param_1 + 0x78))(param_1,L".js=text/javascript");
    (**(code **)(*param_1 + 0x78))(param_1,L".htm=text/html");
    (**(code **)(*param_1 + 0x78))(param_1,L".html=text/html");
    (**(code **)(*param_1 + 0x78))(param_1,L".xhtml=application/xhtml+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".xht=application/xhtml+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".rdf=application/rdf+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".rss=application/rss+xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".ls=text/javascript");
    (**(code **)(*param_1 + 0x78))(param_1,L".mocha=text/javascript");
    (**(code **)(*param_1 + 0x78))(param_1,L".shtml=server-parsed-html");
    (**(code **)(*param_1 + 0x78))(param_1,L".xml=text/xml");
    (**(code **)(*param_1 + 0x78))(param_1,L".sgm=text/sgml");
    (**(code **)(*param_1 + 0x78))(param_1,L".sgml=text/sgml");
    (**(code **)(*param_1 + 0x78))(param_1,L".mht=message/rfc822");
    puVar1 = local_60;
    if (param_2 != '\0') {
      local_28 = FUN_005ea3c0(&DAT_005e7878,1);
      local_20 = (longlong *)FUN_004b6930(&PTR_FUN_00478280,1);
      FUN_005ea670(local_28,0xffffffff80000000);
      cVar2 = FUN_005eaa60(local_28,&DAT_008abbcc);
      if (cVar2 != '\0') {
        FUN_005eb0d0(local_28,local_20);
        FUN_005ea630(local_28);
      }
      iVar3 = (**(code **)(*local_20 + 0x28))();
      local_2c = 0;
      if (-1 < iVar3 + -1) {
        do {
          (**(code **)(*local_20 + 0x18))(local_20,&local_40,local_2c);
          cVar2 = FUN_00879090(local_40,&DAT_008abbdc);
          if ((cVar2 != '\0') && (cVar2 = FUN_005eaa60(local_28,local_40), cVar2 != '\0')) {
            FUN_005eb6d0(local_28,&local_38,L"Content Type");
            local_48 = 0;
            if (local_38 != 0) {
              local_48 = *(int *)(local_38 + -4);
            }
            if (0 < local_48) {
              FUN_00879190(&local_68,local_40);
              FUN_00879190(&local_70,local_38);
              FUN_004b4f10(param_1,local_68,local_70);
            }
            FUN_005ea630(local_28);
          }
          local_2c = local_2c + 1;
          iVar3 = iVar3 + -1;
        } while (iVar3 != 0);
      }
      cVar2 = FUN_005eaa60(local_28,L"\\MIME\\Database\\Content Type");
      if (cVar2 != '\0') {
        (**(code **)(*local_20 + 0x90))(local_20);
        FUN_005eb0d0(local_28,local_20);
        FUN_005ea630(local_28);
        iVar3 = (**(code **)(*local_20 + 0x28))();
        local_2c = 0;
        if (-1 < iVar3 + -1) {
          do {
            (**(code **)(*local_20 + 0x18))(local_20,&local_80,local_2c);
            FUN_00416ba0(&local_78,L"\\MIME\\Database\\Content Type\\",local_80);
            cVar2 = FUN_005eaa60(local_28,local_78);
            if (cVar2 != '\0') {
              FUN_005eb6d0(local_28,&local_88,L"Extension");
              FUN_00879190(&local_40,local_88);
              local_4c = 0;
              if (local_40 != (short *)0x0) {
                local_4c = *(int *)(local_40 + -2);
              }
              if (0 < local_4c) {
                if (*local_40 != 0x2e) {
                  FUN_00416ba0(&local_40,&DAT_008abbdc,local_40);
                }
                (**(code **)(*local_20 + 0x18))(local_20,&local_98,local_2c);
                FUN_00879190(&local_90,local_98);
                FUN_004b4f10(param_1,local_40,local_90);
              }
              FUN_005ea630(local_28);
            }
            local_2c = local_2c + 1;
            iVar3 = iVar3 + -1;
          } while (iVar3 != 0);
        }
      }
      FUN_00410f20(local_20);
      FUN_00410f20(local_28);
      puVar1 = local_60;
    }
  }
  local_60 = puVar1;
  FUN_00414560(&local_98,7);
  FUN_00414560(&local_40,2);
  return;
}

