/* Ghidra address: 01bbf630 */
/* Ghidra symbol: FUN_01bbf630 */


void FUN_01bbf630(longlong param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 longlong param_5,undefined4 param_6,undefined8 param_7)

{
  char cVar1;
  undefined8 uVar2;
  undefined8 local_res10;
  undefined8 local_res18;
  undefined8 local_res20;
  undefined1 auStack_e8 [32];
  undefined8 local_c8;
  undefined8 local_b0;
  undefined8 local_a8;
  undefined8 local_a0;
  undefined8 local_98;
  undefined8 local_90;
  undefined8 local_88;
  undefined8 local_80;
  undefined8 local_78;
  undefined1 *local_70;
  undefined8 local_60;
  undefined8 local_58;
  undefined8 local_50;
  undefined8 local_48;
  longlong local_30;
  longlong local_28;
  undefined2 local_1a;
  
  local_70 = auStack_e8;
  local_b0 = 0;
  local_a8 = 0;
  local_a0 = 0;
  local_98 = 0;
  local_90 = 0;
  local_88 = 0;
  local_80 = 0;
  local_78 = 0;
  local_48 = 0;
  local_50 = 0;
  local_58 = 0;
  local_60 = 0;
  local_res10 = param_2;
  local_res18 = param_3;
  local_res20 = param_4;
  FUN_00414610(param_2);
  FUN_00414610(local_res20);
  FUN_00414610(param_5);
  local_1a = *(undefined2 *)(PTR_DAT_02004830 + 0x17a);
  *(undefined2 *)(PTR_DAT_02004830 + 0x17a) = 0x2e;
  uVar2 = FUN_004b6930(&PTR_FUN_00478280,1);
  *(undefined8 *)(param_1 + 0x58) = uVar2;
  uVar2 = FUN_004b6930(&PTR_FUN_00478280,1);
  *(undefined8 *)(param_1 + 0x50) = uVar2;
  FUN_00414b50(&local_58,L"IBIS Models.dat");
  local_c8 = local_58;
  FUN_00416cd0(&local_60,3,*(undefined8 *)PTR_DAT_020049a0,L"\\SpiceLib\\");
  cVar1 = FUN_00440a20(local_60,1);
  if (cVar1 == '\0') {
    FUN_00416ba0(&local_78,L"File not found: ",local_60);
    FUN_01bbc400(param_1,local_78);
  }
  (**(code **)(**(longlong **)(param_1 + 0x58) + 0xd8))(*(longlong **)(param_1 + 0x58),local_60);
  local_28 = FUN_01bbbbd0(local_res18,1,local_res20);
  if (local_28 == 0) {
    FUN_00416ba0(&local_80,local_res20,L": pin not found");
    FUN_01bbc400(param_1,local_80);
  }
  FUN_01bba520(&local_88,local_res20);
  FUN_00414ad0(param_1 + 0x28,local_88);
  FUN_01bbb5e0(local_28,&local_90,2);
  FUN_00414ad0(param_1 + 0x40,local_90);
  if (param_5 == 0) {
    FUN_00414b50(&param_5,*(undefined8 *)(param_1 + 0x40));
  }
  local_30 = FUN_01bbc0f0(*(undefined8 *)(param_1 + 0x48),*(undefined8 *)(param_1 + 0x40));
  if ((local_30 == 0) && (param_5 != 0)) {
    local_30 = FUN_01bbc0f0(*(undefined8 *)(param_1 + 0x48),param_5);
  }
  if (local_30 == 0) {
    FUN_00416ba0(&local_98,param_5,L": model not found");
    FUN_01bbc400(param_1,local_98);
  }
  *(undefined4 *)(param_1 + 0x20) = param_6;
  (**(code **)(**(longlong **)(param_1 + 0x50) + 0x78))
            (*(longlong **)(param_1 + 0x50),L"* Generated by TINA");
  (**(code **)(**(longlong **)(param_1 + 0x50) + 0x78))(*(longlong **)(param_1 + 0x50),0);
  FUN_00416ba0(&local_a0,L"* Signal name: ",local_res20);
  (**(code **)(**(longlong **)(param_1 + 0x50) + 0x78))(*(longlong **)(param_1 + 0x50),local_a0);
  FUN_00416ba0(&local_a8,L"* Model name: ",*(undefined8 *)(local_30 + 8));
  (**(code **)(**(longlong **)(param_1 + 0x50) + 0x78))(*(longlong **)(param_1 + 0x50),local_a8);
  FUN_00416ba0(&local_b0,L"* Model type: ",*(undefined8 *)(local_30 + 0x10));
  (**(code **)(**(longlong **)(param_1 + 0x50) + 0x78))(*(longlong **)(param_1 + 0x50),local_b0);
  (**(code **)(**(longlong **)(param_1 + 0x50) + 0x78))(*(longlong **)(param_1 + 0x50),0);
  FUN_01bbe1e0(param_1,local_30,*(undefined8 *)(param_1 + 0x58),*(undefined8 *)(param_1 + 0x50));
  FUN_01bbe480(param_1,local_30,*(undefined8 *)(param_1 + 0x50));
  local_c8 = param_7;
  FUN_01bbf020(param_1,local_res18,local_30,local_28);
  (**(code **)(**(longlong **)(param_1 + 0x50) + 0x100))(*(longlong **)(param_1 + 0x50),local_res10)
  ;
  *(undefined2 *)(PTR_DAT_02004830 + 0x17a) = local_1a;
  FUN_00410f20(*(undefined8 *)(param_1 + 0x58));
  FUN_00410f20(*(undefined8 *)(param_1 + 0x50));
  FUN_00414560(&local_b0,8);
  FUN_00414560(&local_60,4);
  FUN_00414480(&local_res10);
  FUN_00414560(&local_res20,2);
  return;
}

