/* Ghidra address: 01561f80 */
/* Ghidra symbol: FUN_01561f80 */


void FUN_01561f80(longlong param_1,int param_2)

{
  longlong *plVar1;
  undefined1 *puVar2;
  char cVar3;
  int iVar4;
  undefined8 uVar5;
  longlong lVar6;
  int iVar7;
  int iVar8;
  undefined1 auStack_1f8 [32];
  wchar_t *local_1d8;
  wchar_t *local_1d0;
  undefined *local_1c8;
  undefined8 local_1c0;
  undefined *local_1b8;
  undefined8 local_1a8;
  undefined8 local_1a0;
  undefined8 local_198;
  undefined1 local_190;
  wchar_t *local_188;
  undefined1 local_180;
  wchar_t *local_178;
  undefined1 local_170;
  undefined8 local_168;
  undefined1 local_160;
  undefined8 local_158;
  undefined1 local_150;
  undefined8 local_148;
  undefined1 local_140;
  undefined8 local_138;
  undefined8 local_130;
  undefined8 local_128;
  undefined8 local_120;
  undefined8 local_118;
  wchar_t *local_110;
  undefined8 local_108;
  undefined8 local_100;
  undefined8 local_f8;
  undefined8 local_f0;
  undefined8 local_e8;
  undefined8 local_e0;
  undefined8 local_d8;
  undefined8 local_d0;
  undefined8 local_c8;
  undefined1 *local_c0;
  int local_ac;
  longlong local_98;
  longlong local_90;
  longlong local_88;
  undefined8 local_80;
  undefined8 local_78;
  undefined8 local_70;
  undefined8 local_68;
  undefined8 local_60;
  undefined8 local_58;
  longlong local_50;
  longlong local_48;
  int local_3c;
  int local_38;
  int local_34;
  int local_30;
  int local_2c;
  longlong *local_28;
  longlong *local_20;
  
  local_c0 = auStack_1f8;
  local_1a8 = 0;
  local_1a0 = 0;
  local_130 = 0;
  local_138 = 0;
  local_128 = 0;
  local_f8 = 0;
  local_120 = 0;
  local_100 = 0;
  local_110 = (wchar_t *)0x0;
  local_118 = 0;
  local_108 = 0;
  local_e8 = 0;
  local_f0 = 0;
  local_d8 = 0;
  local_e0 = 0;
  local_d0 = 0;
  local_c8 = 0;
  local_50 = 0;
  local_58 = 0;
  local_60 = 0;
  local_68 = 0;
  local_70 = 0;
  local_78 = 0;
  local_80 = 0;
  if (param_2 == 1) {
    local_c0 = auStack_1f8;
    FUN_004414c0(&local_c8,*(undefined8 *)(param_1 + 0x728),L".xdc");
    FUN_00414ad0(param_1 + 0x728,local_c8);
    puVar2 = local_c0;
  }
  else {
    puVar2 = auStack_1f8;
    if (param_2 == 2) {
      FUN_004414c0(&local_d0,*(undefined8 *)(param_1 + 0x728),L".qsf");
      FUN_00414ad0(param_1 + 0x728,local_d0);
      puVar2 = local_c0;
    }
  }
  local_c0 = puVar2;
  local_20 = (longlong *)FUN_004b6930(&PTR_FUN_00478280,1);
  (**(code **)(*local_20 + 0x78))
            (local_20,
             L"#***********************************************************************************"
            );
  (**(code **)(*local_20 + 0x78))(local_20,&DAT_01562fcc);
  (**(code **)(*local_20 + 0x78))(local_20,L"#* Generated by TINA");
  (**(code **)(*local_20 + 0x78))(local_20,&DAT_01562fcc);
  (**(code **)(*local_20 + 0x78))
            (local_20,
             L"#***********************************************************************************"
            );
  (**(code **)(*local_20 + 0x78))(local_20,0);
  (**(code **)(*local_20 + 0x78))(local_20,0);
  if ((*(longlong *)PTR_DAT_02001470 != 0) && (0 < *(int *)(*(longlong *)(param_1 + 0x988) + 0x10)))
  {
    local_48 = FUN_004aeac0(*(undefined8 *)(param_1 + 0x988),0);
    local_88 = FUN_01571ef0(*(undefined8 *)(param_1 + 0x750),*(undefined4 *)(local_48 + 8));
    if (local_88 == 0) {
      FUN_01d43440(&local_e0,*(undefined4 *)(local_48 + 8));
      local_1d8 = L" not found in TConvertVHDL.create_ucf_file";
      FUN_00416cd0(&local_d8,3,&DAT_01563018,local_e0);
      FUN_016fd940(local_d8);
    }
    FUN_01550c40(param_1,&local_58,local_88);
    local_3c = FUN_00b905f0(*(undefined4 *)(local_48 + 0xc),
                            *(undefined4 *)(*(longlong *)PTR_DAT_02001470 + 0x10));
    local_90 = FUN_004aeac0(*(undefined8 *)PTR_DAT_02001470,local_3c);
    cVar3 = FUN_01561ef0(*(undefined8 *)(local_90 + 8));
    if ((cVar3 != '\0') && (param_2 != 2)) {
      uVar5 = FUN_0044d490(&PTR_FUN_004334c0,1,
                           L"This circuit can be exported only for Intel Quartus!");
      FUN_004134c0(uVar5);
    }
    cVar3 = FUN_01561ef0(*(undefined8 *)(local_90 + 8));
    if ((cVar3 == '\0') && (param_2 == 2)) {
      uVar5 = FUN_0044d490(&PTR_FUN_004334c0,1,L"This circuit can be exported only for Xilinx!");
      FUN_004134c0(uVar5);
    }
    iVar7 = *(int *)(*(longlong *)(param_1 + 0x988) + 0x10);
    local_34 = 0;
    if (-1 < iVar7 + -1) {
      do {
        local_48 = FUN_004aeac0(*(undefined8 *)(param_1 + 0x988),local_34);
        if (*(int *)(local_48 + 0xc) != local_3c) {
          local_88 = FUN_01571ef0(*(undefined8 *)(param_1 + 0x750),*(undefined4 *)(local_48 + 8));
          if (local_88 == 0) {
            FUN_01d43440(&local_f0,*(undefined4 *)(local_48 + 8));
            local_1d8 = L" not found in TConvertVHDL.create_ucf_file";
            FUN_00416cd0(&local_e8,3,&DAT_01563018,local_f0);
            FUN_016fd940(local_e8);
          }
          FUN_01550c40(param_1,&local_60,local_88);
          FUN_00415dd0(&local_108,local_58,0);
          FUN_015f15d0(&local_100,local_108);
          FUN_00415dd0(&local_118,local_60,0);
          FUN_015f15d0(&local_110,local_118);
          local_1d8 = L"\x202c";
          local_1d0 = local_110;
          FUN_00415980(&local_f8,4,
                       "Error while generating constraint file: the following pins are in different devices: "
                       ,local_100);
          FUN_00416880(&local_120,local_f8);
          uVar5 = FUN_0044d490(&PTR_FUN_004334c0,1,local_120);
          FUN_004134c0(uVar5);
        }
        local_34 = local_34 + 1;
        iVar7 = iVar7 + -1;
      } while (iVar7 != 0);
    }
    iVar7 = *(int *)(*(longlong *)(local_90 + 0x10) + 0x10);
    local_30 = 0;
    if (-1 < iVar7 + -1) {
      do {
        local_98 = FUN_004aeac0(*(undefined8 *)(local_90 + 0x10),local_30);
        FUN_00416ba0(&local_128,&DAT_015631e4,*(undefined8 *)(local_98 + 8));
        (**(code **)(*local_20 + 0x78))(local_20,local_128);
        iVar8 = *(int *)(*(longlong *)(param_1 + 0x988) + 0x10);
        local_34 = 0;
        if (-1 < iVar8 + -1) {
          do {
            local_48 = FUN_004aeac0(*(undefined8 *)(param_1 + 0x988),local_34);
            if (*(int *)(local_48 + 0x10) == local_30) {
              local_88 = FUN_01571ef0(*(undefined8 *)(param_1 + 0x750),*(undefined4 *)(local_48 + 8)
                                     );
              if (local_88 == 0) {
                FUN_01d43440(&local_138,*(undefined4 *)(local_48 + 8));
                local_1d8 = L" not found in TConvertVHDL.create_ucf_file";
                FUN_00416cd0(&local_130,3,&DAT_01563018,local_138);
                FUN_016fd940(local_130);
              }
              FUN_01550c40(param_1,&local_60,local_88);
              if (*(int *)(*(longlong *)(local_98 + 0x18) + 0x10) + -1 < *(int *)(local_48 + 0x14))
              {
                uVar5 = FUN_0044d490(&PTR_FUN_004334c0,1,L"Error while generating constraint file");
                FUN_004134c0(uVar5);
              }
              lVar6 = FUN_004aeac0(*(undefined8 *)(local_98 + 0x18),*(undefined4 *)(local_48 + 0x14)
                                  );
              FUN_00414b50(&local_68,*(undefined8 *)(lVar6 + 0x10));
              lVar6 = FUN_004aeac0(*(undefined8 *)(local_98 + 0x18),*(undefined4 *)(local_48 + 0x14)
                                  );
              FUN_00414b50(&local_70,*(undefined8 *)(lVar6 + 8));
              if (param_2 == 1) {
                local_158 = local_68;
                local_150 = 0x11;
                local_148 = local_60;
                local_140 = 0x11;
                FUN_00442f70(&local_78,L"set_property PACKAGE_PIN %s [get_ports %s]",&local_158,1);
                (**(code **)(*local_20 + 0x78))(local_20,local_78);
                local_188 = L"IOSTANDARD";
                local_180 = 0x11;
                local_178 = L"LVCMOS33";
                local_170 = 0x11;
                local_168 = local_60;
                local_160 = 0x11;
                FUN_00442f70(&local_78,L"set_property %s %s [get_ports %s]",&local_188,2);
                (**(code **)(*local_20 + 0x78))(local_20,local_78);
                iVar4 = FUN_00416db0(*(undefined8 *)(local_98 + 8),L"Clock");
                if (iVar4 == 0) {
                  local_198 = local_60;
                  local_190 = 0x11;
                  FUN_00442f70(&local_78,
                               L"create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports %s]"
                               ,&local_198,0);
                  (**(code **)(*local_20 + 0x78))(local_20,local_78);
                }
                iVar4 = FUN_00416db0(*(undefined8 *)(local_98 + 8),L"USB HID (PS/2)");
                if (iVar4 == 0) {
                  local_188 = L"PULLUP";
                  local_180 = 0x11;
                  local_178 = L"true";
                  local_170 = 0x11;
                  local_168 = local_60;
                  local_160 = 0x11;
                  FUN_00442f70(&local_78,L"set_property %s %s [get_ports %s]",&local_188,2);
                  (**(code **)(*local_20 + 0x78))(local_20,local_78);
                }
              }
              else if (param_2 == 0) {
                lVar6 = FUN_004aeac0(*(undefined8 *)(local_98 + 0x18),
                                     *(undefined4 *)(local_48 + 0x14));
                local_1d8 = L"\"";
                local_1d0 = L" LOC = ";
                local_1c8 = &DAT_01563488;
                local_1c0 = *(undefined8 *)(lVar6 + 0x10);
                local_1b8 = &DAT_015634b4;
                FUN_00416cd0(&local_1a0,7,L"NET \"",local_60);
                (**(code **)(*local_20 + 0x78))(local_20,local_1a0);
                if (*(char *)(local_98 + 0x20) != '\0') {
                  local_1d8 = L"\"";
                  local_1d0 = L" PULLUP";
                  local_1c8 = &DAT_015634e4;
                  FUN_00416cd0(&local_1a8,5,L"NET \"",local_60);
                  (**(code **)(*local_20 + 0x78))(local_20,local_1a8);
                }
              }
              else if (param_2 == 2) {
                local_158 = local_68;
                local_150 = 0x11;
                local_148 = local_60;
                local_140 = 0x11;
                FUN_00442f70(&local_78,L"set_location_assignment %s -to %s",&local_158,1);
                (**(code **)(*local_20 + 0x78))(local_20,local_78);
                iVar4 = FUN_00416db0(*(undefined8 *)(local_98 + 8),&DAT_01563544);
                if ((iVar4 == 0) ||
                   ((iVar4 = FUN_00416db0(*(undefined8 *)(local_98 + 8),L"Arduino"), iVar4 == 0 &&
                    (iVar4 = FUN_00416db0(local_70,L"ARDUINO_RESET_N"), iVar4 == 0)))) {
                  FUN_00414b50(&local_80,L"3.3 V SCHMITT TRIGGER");
                }
                else {
                  FUN_00414b50(&local_80,L"3.3-V LVTTL");
                }
                local_158 = local_80;
                local_150 = 0x11;
                local_148 = local_60;
                local_140 = 0x11;
                FUN_00442f70(&local_78,L"set_instance_assignment -name IO_STANDARD \"%s\" -to %s",
                             &local_158,1);
                (**(code **)(*local_20 + 0x78))(local_20,local_78);
              }
            }
            local_34 = local_34 + 1;
            iVar8 = iVar8 + -1;
          } while (iVar8 != 0);
        }
        (**(code **)(*local_20 + 0x78))(local_20,0);
        (**(code **)(*local_20 + 0x78))(local_20,0);
        local_30 = local_30 + 1;
        iVar7 = iVar7 + -1;
      } while (iVar7 != 0);
    }
  }
  (**(code **)(**(longlong **)(param_1 + 0x908) + 0x88))(*(longlong **)(param_1 + 0x908),local_20);
  local_28 = (longlong *)FUN_004b6930(&PTR_FUN_00478280,1);
  plVar1 = *(longlong **)(param_1 + 0x908);
  iVar7 = (**(code **)(*plVar1 + 0x28))(plVar1);
  local_1d8 = L"_";
  local_1d0 = (wchar_t *)CONCAT71(local_1d0._1_7_,1);
  FUN_015fba60(plVar1,0,iVar7 + -1,&PTR_u_HAN__01563674);
  iVar7 = (**(code **)(**(longlong **)(param_1 + 0x990) + 0x28))();
  local_30 = 0;
  if (-1 < iVar7 + -1) {
    do {
      (**(code **)(**(longlong **)(param_1 + 0x990) + 0x18))
                (*(longlong **)(param_1 + 0x990),&local_50,local_30);
      local_ac = 0;
      if (local_50 != 0) {
        local_ac = *(int *)(local_50 + -4);
      }
      local_38 = local_ac;
      local_2c = FUN_004170c0(&DAT_0156369c,local_50,1);
      if (local_2c == 1) {
        local_2c = FUN_004170c0(&LAB_015636b0,local_50,1);
        FUN_00416dc0(&local_50,local_50,local_2c + 1,local_38 - local_2c);
        (**(code **)(*local_28 + 0xd8))(local_28,local_50);
        iVar8 = (**(code **)(*local_28 + 0x28))(local_28);
        local_1d8 = L"_";
        local_1d0 = (wchar_t *)CONCAT71(local_1d0._1_7_,1);
        FUN_015fba60(local_28,0,iVar8 + -1,&PTR_u_HAN__01563674);
        (**(code **)(*local_28 + 0x100))(local_28,local_50);
      }
      local_30 = local_30 + 1;
      iVar7 = iVar7 + -1;
    } while (iVar7 != 0);
  }
  FUN_00410f20(local_28);
  FUN_00410f20(local_20);
  FUN_00414560(&local_1a8,2);
  FUN_00414560(&local_138,4);
  FUN_00414590(&local_118,5);
  FUN_00414560(&local_f0,6);
  FUN_00414560(&local_80,7);
  return;
}

