/* Ghidra address: 01ce92d0 */
/* Ghidra symbol: FUN_01ce92d0 */


void FUN_01ce92d0(longlong param_1,undefined8 param_2)

{
  longlong lVar1;
  char cVar2;
  int iVar3;
  undefined4 uVar4;
  undefined8 uVar5;
  undefined8 local_res10 [3];
  undefined1 auStack_568 [32];
  undefined *local_548;
  undefined *local_540;
  undefined *local_538;
  undefined8 local_530;
  undefined *local_528;
  int local_518;
  int local_514;
  undefined8 local_510;
  undefined *local_508;
  undefined8 local_500;
  undefined *local_4f8;
  undefined *local_4f0;
  undefined8 local_4e8;
  undefined8 local_4e0;
  undefined8 local_4d8;
  undefined8 local_4d0;
  undefined8 local_4c8;
  undefined8 local_4c0;
  undefined8 local_4b8;
  undefined8 local_4b0;
  undefined8 local_4a8;
  undefined8 local_4a0;
  undefined8 local_498;
  undefined8 local_490;
  undefined8 local_488;
  undefined8 local_480;
  undefined8 local_478;
  undefined8 local_470;
  undefined8 local_468;
  undefined8 local_460;
  undefined8 local_458;
  undefined8 local_450;
  undefined8 local_448;
  undefined1 *local_440;
  undefined8 local_430;
  undefined8 local_428;
  undefined8 local_420;
  undefined8 local_418;
  undefined8 local_410;
  undefined8 local_408;
  longlong local_3f8;
  undefined8 *local_3e8;
  undefined8 local_3e0;
  undefined8 local_3d8;
  undefined8 local_3d0;
  undefined8 local_3c8;
  undefined8 local_3b8;
  undefined8 *local_3b0;
  undefined8 *local_3a8;
  longlong *local_3a0;
  longlong *local_398;
  undefined8 local_390;
  undefined8 local_388;
  undefined8 local_380;
  undefined8 local_378;
  undefined8 local_370;
  int local_360;
  int local_35c;
  int local_358;
  undefined2 local_352;
  undefined8 local_350;
  undefined *local_348;
  undefined8 local_340;
  undefined8 local_338;
  undefined8 local_330;
  undefined8 local_328;
  undefined8 local_320;
  undefined8 local_318;
  undefined1 local_310 [760];
  
  local_440 = auStack_568;
  local_510 = 0;
  local_508 = (undefined *)0x0;
  local_500 = 0;
  local_4f8 = (undefined *)0x0;
  local_4f0 = (undefined *)0x0;
  local_4e0 = 0;
  local_4e8 = 0;
  local_4d8 = 0;
  local_4c8 = 0;
  local_4d0 = 0;
  local_4c0 = 0;
  local_4b8 = 0;
  local_4a8 = 0;
  local_4b0 = 0;
  local_498 = 0;
  local_4a0 = 0;
  local_488 = 0;
  local_490 = 0;
  local_478 = 0;
  local_480 = 0;
  local_468 = 0;
  local_470 = 0;
  local_460 = 0;
  local_458 = 0;
  local_448 = 0;
  local_450 = 0;
  local_378 = 0;
  local_380 = 0;
  local_388 = 0;
  local_390 = 0;
  local_318 = 0;
  local_320 = 0;
  local_328 = 0;
  local_330 = 0;
  local_338 = 0;
  local_340 = 0;
  local_350 = 0;
  local_348 = (undefined *)0x0;
  local_res10[0] = param_2;
  FUN_00414610(param_2);
  FUN_0040cf10(local_310,local_res10[0],0);
  FUN_00409900();
  FUN_0040ca00(local_310);
  FUN_00409900();
  FUN_00414480(&local_378);
  FUN_00414480(&local_388);
  local_352 = *(undefined2 *)(PTR_DAT_02004830 + 0x17a);
  *(undefined2 *)(PTR_DAT_02004830 + 0x17a) = 0x2e;
  uVar5 = (**(code **)(**(longlong **)(param_1 + 0x80) + 0x30))(*(longlong **)(param_1 + 0x80),0);
  cVar2 = FUN_004113d0(uVar5,&PTR_FUN_01aae560);
  if (cVar2 != '\0') {
    local_370 = (**(code **)(**(longlong **)(param_1 + 0x80) + 0x30))
                          (*(longlong **)(param_1 + 0x80),0);
    FUN_00414b50(&local_380,
                 L"#H\r\nSOURCE=\'TINA\' VERSION=\'%VERSION%\'\r\nTITLE=\'* Generated by TINA\'\r\nSUBTITLE=\'%SUBTITLE%\'\r\nTIME=\'%TIME%\' DATE=\'%DATE%\' TEMPERATURE=\'2.7000000E01\'\r\nANALYSIS=\'%ANALYSIS%\' SERIALNO=\'12345\'\r\nALLVALUES=\'NO\' COMPLEXVALUES=\'%COMPLEX%\' NODES=\'%NODES%\'\r\nSWEEPVAR=\'%SWEEPVAR%\' SWEEPMODE=\'%SWEEPMODE%\'\r\nXBEGIN=\'%XBEGIN%\' XEND=\'%XEND%\'\r\nFORMAT=\'%FORMAT%\'\r\nDGTLDATA=\'NO\'"
                );
    FUN_00416ba0(&local_450,L"TINA ",*(undefined8 *)PTR_DAT_02004728);
    local_548._0_1_ = 3;
    FUN_00450070(&local_448,local_380,L"%VERSION%",local_450);
    FUN_00414b50(&local_380,local_448);
    FUN_00414480(&local_318);
    local_408 = FUN_00448ed0();
    FUN_0044a300(&local_318,local_408,PTR_DAT_02004830);
    local_548._0_1_ = 3;
    FUN_00450070(&local_458,local_380,L"%TIME%",local_318);
    FUN_00414b50(&local_380,local_458);
    FUN_00414480(&local_318);
    FUN_00414480(&local_320);
    local_410 = FUN_00448ed0();
    FUN_0044a2b0(&local_320,local_410,PTR_DAT_02004830);
    local_548._0_1_ = 3;
    FUN_00450070(&local_460,local_380,L"%DATE%",local_320);
    FUN_00414b50(&local_380,local_460);
    FUN_00414480(&local_320);
    FUN_01ce8c60(auStack_568,&local_470,local_370,L"%ANALYSIS%");
    local_548._0_1_ = 3;
    FUN_00450070(&local_468,local_380,L"%ANALYSIS%",local_470);
    FUN_00414b50(&local_380,local_468);
    FUN_01ce8c60(auStack_568,&local_480,local_370,L"%COMPLEX%");
    local_548._0_1_ = 3;
    FUN_00450070(&local_478,local_380,L"%COMPLEX%",local_480);
    FUN_00414b50(&local_380,local_478);
    FUN_01ce8c60(auStack_568,&local_490,local_370,L"%SWEEPVAR%");
    local_548._0_1_ = 3;
    FUN_00450070(&local_488,local_380,L"%SWEEPVAR%",local_490);
    FUN_00414b50(&local_380,local_488);
    FUN_01ce8c60(auStack_568,&local_4a0,local_370,L"%SWEEPMODE%");
    local_548._0_1_ = 3;
    FUN_00450070(&local_498,local_380,L"%SWEEPMODE%",local_4a0);
    FUN_00414b50(&local_380,local_498);
    FUN_01ce8c60(auStack_568,&local_4b0,local_370,L"%FORMAT%");
    local_548._0_1_ = 3;
    FUN_00450070(&local_4a8,local_380,L"%FORMAT%",local_4b0);
    FUN_00414b50(&local_380,local_4a8);
    FUN_00414480(&local_328);
    uVar5 = (**(code **)(**(longlong **)(param_1 + 0x80) + 0x30))(*(longlong **)(param_1 + 0x80),0);
    local_418 = FUN_01ab2a30(uVar5);
    FUN_00448450(&local_328,local_418,PTR_DAT_02004830);
    local_548._0_1_ = 3;
    FUN_00450070(&local_4b8,local_380,L"%XBEGIN%",local_328);
    FUN_00414b50(&local_380,local_4b8);
    FUN_00414480(&local_328);
    FUN_00414480(&local_330);
    uVar5 = (**(code **)(**(longlong **)(param_1 + 0x80) + 0x30))(*(longlong **)(param_1 + 0x80),0);
    local_420 = FUN_01ab2a60(uVar5);
    FUN_00448450(&local_330,local_420,PTR_DAT_02004830);
    local_548 = (undefined *)CONCAT71(local_548._1_7_,3);
    FUN_00450070(&local_4c0,local_380,L"%XEND%",local_330);
    FUN_00414b50(&local_380,local_4c0);
    FUN_00414480(&local_330);
    local_398 = (longlong *)FUN_004b6930(&PTR_FUN_00478280,1);
    local_3a0 = (longlong *)FUN_00410e60(&PTR_FUN_00472dd0,1);
    iVar3 = (**(code **)(**(longlong **)(param_1 + 0x80) + 0x28))();
    local_518 = iVar3 + -1;
    local_358 = 0;
    if (-1 < local_518) {
      do {
        local_518 = iVar3;
        local_3f8 = (**(code **)(**(longlong **)(param_1 + 0x80) + 0x30))
                              (*(longlong **)(param_1 + 0x80),local_358);
        lVar1 = *(longlong *)(local_3f8 + 0xe0);
        if ((*(int *)(lVar1 + 0x154) == 0) && (*(char *)(lVar1 + 8) == '\0')) {
          local_360 = (**(code **)(**(longlong **)(local_3f8 + 200) + 0x20))
                                (*(longlong **)(local_3f8 + 200),lVar1,0);
          *(undefined8 *)PTR_DAT_02005620 = 0;
          *(undefined8 *)PTR_DAT_020041f8 = 0;
          local_3a8 = (undefined8 *)FUN_004095c0((longlong)local_360);
          (**(code **)(*local_3a0 + 0x10))(local_3a0);
          (**(code **)(*local_398 + 0x90))(local_398);
          FUN_01cc6ed0(*(undefined8 *)(local_3f8 + 0xd0),*(undefined8 *)(local_3f8 + 0xe0),local_3a0
                      );
          iVar3 = (int)local_3a0[2];
          local_35c = 0;
          if (-1 < iVar3 + -1) {
            do {
              uVar5 = FUN_004aeac0(local_3a0,local_35c);
              FUN_01cc0ae0(uVar5,&local_4d0);
              FUN_01ce7c10(&local_4c8,local_4d0);
              (**(code **)(*local_398 + 0x78))(local_398,local_4c8);
              local_35c = local_35c + 1;
              iVar3 = iVar3 + -1;
            } while (iVar3 != 0);
          }
          uVar5 = (**(code **)(**(longlong **)(param_1 + 0x80) + 0x30))
                            (*(longlong **)(param_1 + 0x80),local_358);
          FUN_01ce8c60(auStack_568,&local_4d8,uVar5,L"%SUBTITLE%");
          local_548._0_1_ = 3;
          FUN_00450070(&local_378,local_380,L"%SUBTITLE%",local_4d8);
          uVar4 = (**(code **)(*local_398 + 0x28))(local_398);
          FUN_0043f750(&local_4e8,uVar4);
          local_548 = (undefined *)CONCAT71(local_548._1_7_,3);
          FUN_00450070(&local_4e0,local_378,L"%NODES%",local_4e8);
          FUN_00414b50(&local_378,local_4e0);
          FUN_01ce8c10(auStack_568,&local_378);
          uVar5 = FUN_0040f200(local_310,&DAT_01cea7c0);
          FUN_0040f590(uVar5);
          FUN_00409900();
          FUN_00414480(&local_378);
          iVar3 = (**(code **)(*local_398 + 0x28))();
          local_35c = 0;
          if (-1 < iVar3 + -1) {
            do {
              (**(code **)(*local_398 + 0x18))(local_398,&local_4f0,local_35c);
              local_548 = local_4f0;
              local_540 = &DAT_01cea7e4;
              FUN_00416cd0(&local_378,4,local_378,&DAT_01cea7d4);
              FUN_01ce8bc0(auStack_568,&local_378);
              local_35c = local_35c + 1;
              iVar3 = iVar3 + -1;
            } while (iVar3 != 0);
          }
          FUN_01ce8c10(auStack_568,&local_378);
          while (cVar2 = (**(code **)(**(longlong **)(local_3f8 + 200) + 0x40))
                                   (*(longlong **)(local_3f8 + 200),&local_3b8), cVar2 != '\0') {
            FUN_00414480(&local_338);
            FUN_00448450(&local_338,local_3b8,PTR_DAT_02004830);
            FUN_0043f750(&local_4f8,(int)local_3a0[2]);
            local_548 = &DAT_01cea80c;
            local_540 = local_4f8;
            FUN_00416cd0(&local_378,4,&DAT_01cea7f8,local_338);
            FUN_00414480(&local_338);
            FUN_01ce8c10(auStack_568,&local_378);
            local_3b0 = local_3a8;
            iVar3 = *(int *)(*(longlong *)(local_3f8 + 0xe0) + 0x150);
            local_514 = iVar3 + -1;
            local_35c = 0;
            if (-1 < local_514) {
              do {
                local_514 = iVar3;
                uVar5 = FUN_004aeac0(local_3a0,local_35c);
                FUN_01cc0ae0(uVar5,&local_500);
                FUN_01ce7c10(&local_390,local_500);
                iVar3 = (**(code **)(*local_398 + 0xb0))(local_398,local_390);
                *(int *)(local_3f8 + 0xe8) = iVar3 + 1;
                local_3e8 = local_3b0;
                cVar2 = *(char *)(*(longlong *)(local_3f8 + 0xe0) + 0x2b);
                if (cVar2 == '\0') {
                  FUN_00414480(&local_340);
                  local_428 = *local_3e8;
                  FUN_00448450(&local_340,local_428,PTR_DAT_02004830);
                  FUN_0043fba0(&local_508,*(undefined4 *)(local_3f8 + 0xe8),1);
                  local_548 = &DAT_01cea81c;
                  local_540 = local_508;
                  local_538 = &DAT_01cea80c;
                  FUN_00416cd0(&local_378,5,local_378,local_340);
                  FUN_00414480(&local_340);
                  FUN_00b909d0(&local_3b0,8);
                }
                else if (cVar2 == '\x01') {
                  local_3d0 = *local_3b0;
                  FUN_00b909d0(&local_3b0,8);
                  local_3e8 = local_3b0;
                  local_3c8 = *local_3b0;
                  FUN_00b909d0(&local_3b0,8);
                  FUN_00c44940(&local_3e0,&local_3d0);
                  FUN_00414480(&local_350);
                  FUN_00448450(&local_350,local_3e0,PTR_DAT_02004830);
                  FUN_00414480(&local_348);
                  local_430 = local_3d8;
                  FUN_00448450(&local_348,local_3d8,PTR_DAT_02004830);
                  FUN_0043fba0(&local_510,*(undefined4 *)(local_3f8 + 0xe8),1);
                  local_548 = &DAT_01cea82c;
                  local_540 = local_348;
                  local_538 = &DAT_01cea81c;
                  local_530 = local_510;
                  local_528 = &DAT_01cea80c;
                  FUN_00416cd0(&local_378,7,local_378,local_350);
                  FUN_00414480(&local_348);
                  FUN_00414480(&local_350);
                }
                FUN_01ce8bc0(auStack_568,&local_378);
                local_35c = local_35c + 1;
                local_514 = local_514 + -1;
                iVar3 = local_514;
              } while (local_514 != 0);
            }
            FUN_01ce8c10(auStack_568,&local_378);
          }
          FUN_004095f0(local_3a8);
          uVar5 = FUN_0040f200(local_310,&LAB_01cea83c);
          FUN_0040f590(uVar5);
          FUN_00409900();
        }
        local_358 = local_358 + 1;
        local_518 = local_518 + -1;
        iVar3 = local_518;
      } while (local_518 != 0);
    }
    FUN_00410f20(local_3a0);
    FUN_00410f20(local_398);
  }
  FUN_0040d150(local_310);
  FUN_00409900();
  *(undefined2 *)(PTR_DAT_02004830 + 0x17a) = local_352;
  FUN_00414560(&local_510,0x1a);
  FUN_00414560(&local_390,4);
  FUN_00414560(&local_350,8);
  FUN_00414480(local_res10);
  return;
}

