[package]
name = "tiara-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Iced user interface for TIARA"
license.workspace = true
repository.workspace = true

[dependencies]
csv.workspace = true
iced = { workspace = true, features = ["image", "tokio"] }
iced_aw.workspace = true
rfd.workspace = true
tiara-core = { path = "../tiara-core" }
walkdir.workspace = true
xmltree.workspace = true

[lints]
workspace = true
