//! Iced state adapters for recovered text and pin property dialogs.
//!
//! The models are narrow value types and do not depend on active `ShapeEdit` or
//! catalog-editor internals. `iced` supplies messages and widgets. The standard
//! library supplies fixed direction state. Existing `rfd` and `iced_aw` were
//! evaluated, but neither supplies the recovered native font-dialog contract,
//! so font selection stays behind the injected [`FontPicker`] trait.

use iced::widget::{button, column, container, row, text, text_input};
use iced::{Element, Length, Task};

pub const TEXT_PROPERTIES_TITLE: &str = "Text properties";
pub const TEXT_PROPERTIES_FORM_RESOURCE: &str = "TextProps";
pub const PIN_PROPERTIES_TITLE: &str = "Pin properties";
pub const PIN_PROPERTIES_FORM_RESOURCE: &str = "PinProps";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShapeTextValue {
    pub text: String,
    pub font: ShapeFontValue,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShapeFontValue {
    pub family: String,
    pub point_size: u16,
    pub style: FontStyle,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum FontStyle {
    #[default]
    Regular,
    Bold,
    Italic,
    BoldItalic,
}

pub trait FontPicker {
    type Error;

    /// Executes the platform font picker.
    ///
    /// # Errors
    ///
    /// Returns the platform adapter error. The Boolean indicates whether the
    /// user accepted the native picker.
    fn execute(&mut self) -> Result<bool, Self::Error>;
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModalResult {
    Accept,
    Cancel,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TextPropertiesMessage {
    TextChanged(String),
    FontPressed,
    Accept,
    Cancel,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TextPropertiesWindow {
    original: ShapeTextValue,
    working: ShapeTextValue,
    font_picker_requested: bool,
    modal_result: Option<ModalResult>,
}

impl TextPropertiesWindow {
    #[must_use]
    pub fn new(value: ShapeTextValue) -> Self {
        Self {
            original: value.clone(),
            working: value,
            font_picker_requested: false,
            modal_result: None,
        }
    }

    pub fn update(&mut self, message: TextPropertiesMessage) -> Task<TextPropertiesMessage> {
        match message {
            TextPropertiesMessage::TextChanged(value) => self.working.text = value,
            TextPropertiesMessage::FontPressed => self.font_picker_requested = true,
            TextPropertiesMessage::Accept => self.modal_result = Some(ModalResult::Accept),
            TextPropertiesMessage::Cancel => {
                self.working.clone_from(&self.original);
                self.modal_result = Some(ModalResult::Cancel);
            }
        }
        Task::none()
    }

    /// Opens the font-selection dialog and ignores its Boolean result.
    ///
    /// Reimplements Ghidra function `FUN_017a11f0` at `0x017A11F0`. Accepted
    /// and cancelled results have the same observable effect: this handler does
    /// not copy a selected font into the staged text value. Picker errors are
    /// not caught and return through the adapter boundary.
    ///
    /// # Errors
    ///
    /// Returns the injected font-picker error.
    pub fn open_font_picker<P: FontPicker>(&mut self, picker: &mut P) -> Result<(), P::Error> {
        let _ignored_result = picker.execute()?;
        self.font_picker_requested = false;
        Ok(())
    }

    /// Executes one pending font request generated by the Iced update logic.
    ///
    /// # Errors
    ///
    /// Returns the injected font-picker error.
    pub fn run_pending_font_picker<P: FontPicker>(
        &mut self,
        picker: &mut P,
    ) -> Result<bool, P::Error> {
        if !self.font_picker_requested {
            return Ok(false);
        }
        self.open_font_picker(picker)?;
        Ok(true)
    }

    pub fn commit_to(&self, value: &mut ShapeTextValue) -> bool {
        if self.modal_result != Some(ModalResult::Accept) {
            return false;
        }
        value.clone_from(&self.working);
        true
    }

    #[must_use]
    pub const fn working(&self) -> &ShapeTextValue {
        &self.working
    }

    #[must_use]
    pub const fn font_picker_requested(&self) -> bool {
        self.font_picker_requested
    }

    #[must_use]
    pub fn view(&self) -> Element<'_, TextPropertiesMessage> {
        let content = column![
            text(TEXT_PROPERTIES_TITLE).size(18),
            text_input("Text", &self.working.text).on_input(TextPropertiesMessage::TextChanged),
            text(format!(
                "{} {} pt",
                self.working.font.family, self.working.font.point_size
            )),
            row![
                button("Font...").on_press(TextPropertiesMessage::FontPressed),
                button("OK").on_press(TextPropertiesMessage::Accept),
                button("Cancel").on_press(TextPropertiesMessage::Cancel)
            ]
            .spacing(8),
        ]
        .spacing(10);
        container(content)
            .padding(16)
            .width(Length::Fill)
            .height(Length::Fill)
            .into()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PinDirection {
    East,
    South,
    West,
    North,
}

impl PinDirection {
    pub const ALL: [Self; 4] = [Self::North, Self::East, Self::South, Self::West];

    #[must_use]
    pub const fn code(self) -> u8 {
        match self {
            Self::East => 0,
            Self::South => 1,
            Self::West => 2,
            Self::North => 3,
        }
    }

    const fn index(self) -> usize {
        match self {
            Self::North => 0,
            Self::East => 1,
            Self::South => 2,
            Self::West => 3,
        }
    }

    const fn label(self) -> &'static str {
        match self {
            Self::North => "North",
            Self::East => "East",
            Self::South => "South",
            Self::West => "West",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DirectionCode(pub u8);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DirectionSender {
    SpeedButton { tag: i64 },
    Other,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct DirectionButtons {
    down: [bool; 4],
    setter_calls: [u32; 4],
}

impl DirectionButtons {
    /// Reads the selected direction code from the four buttons.
    ///
    /// Reimplements Ghidra function `FUN_017a1f60` at `0x017A1F60`. The read
    /// order is North, East, South, West. No selected button also returns East
    /// code 0.
    #[must_use]
    pub const fn selected_direction_code(&self) -> DirectionCode {
        if self.down[PinDirection::North.index()] {
            DirectionCode(3)
        } else if self.down[PinDirection::East.index()] {
            DirectionCode(0)
        } else if self.down[PinDirection::South.index()] {
            DirectionCode(1)
        } else if self.down[PinDirection::West.index()] {
            DirectionCode(2)
        } else {
            DirectionCode(0)
        }
    }

    /// Changes one direction button only when its state differs.
    ///
    /// Reimplements Ghidra function `FUN_017a1fc0` at `0x017A1FC0`. The return
    /// value reports whether the speed-button setter had to run.
    pub const fn set_button_if_changed(
        &mut self,
        direction: PinDirection,
        requested_down: bool,
    ) -> bool {
        let index = direction.index();
        if self.down[index] == requested_down {
            return false;
        }
        self.down[index] = requested_down;
        self.setter_calls[index] = self.setter_calls[index].saturating_add(1);
        true
    }

    /// Applies one direction code to all four speed buttons.
    ///
    /// Reimplements Ghidra function `FUN_017a1fe0` at `0x017A1FE0`. Codes 0,
    /// 1, 2, and 3 select East, South, West, and North. Any other code clears
    /// all buttons through the set-if-changed helper.
    pub const fn apply_direction_code(&mut self, code: DirectionCode) {
        self.set_button_if_changed(PinDirection::North, code.0 == 3);
        self.set_button_if_changed(PinDirection::East, code.0 == 0);
        self.set_button_if_changed(PinDirection::South, code.0 == 1);
        self.set_button_if_changed(PinDirection::West, code.0 == 2);
    }

    /// Routes a compatible speed-button sender to the direction setter.
    ///
    /// Reimplements Ghidra function `FUN_017a2230` at `0x017A2230`. A
    /// non-speed-button sender is a no-op. A speed button supplies the low byte
    /// of its Tag, including unsupported codes that clear all directions.
    pub const fn route_direction_click(&mut self, sender: DirectionSender) -> bool {
        let DirectionSender::SpeedButton { tag } = sender else {
            return false;
        };
        self.apply_direction_code(DirectionCode(tag.to_le_bytes()[0]));
        true
    }

    #[must_use]
    pub const fn is_down(&self, direction: PinDirection) -> bool {
        self.down[direction.index()]
    }

    #[must_use]
    pub const fn setter_call_count(&self, direction: PinDirection) -> u32 {
        self.setter_calls[direction.index()]
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PinPropertiesValue {
    pub direction: DirectionCode,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PinPropertiesMessage {
    DirectionPressed(PinDirection),
    Accept,
    Cancel,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PinPropertiesWindow {
    original: PinPropertiesValue,
    working: PinPropertiesValue,
    buttons: DirectionButtons,
    modal_result: Option<ModalResult>,
}

impl PinPropertiesWindow {
    #[must_use]
    pub const fn new(value: PinPropertiesValue) -> Self {
        let mut buttons = DirectionButtons {
            down: [false; 4],
            setter_calls: [0; 4],
        };
        buttons.apply_direction_code(value.direction);
        Self {
            original: value,
            working: value,
            buttons,
            modal_result: None,
        }
    }

    pub fn update(&mut self, message: PinPropertiesMessage) -> Task<PinPropertiesMessage> {
        match message {
            PinPropertiesMessage::DirectionPressed(direction) => {
                self.buttons
                    .route_direction_click(DirectionSender::SpeedButton {
                        tag: i64::from(direction.code()),
                    });
            }
            PinPropertiesMessage::Accept => {
                self.working.direction = self.buttons.selected_direction_code();
                self.modal_result = Some(ModalResult::Accept);
            }
            PinPropertiesMessage::Cancel => {
                self.working = self.original;
                self.buttons.apply_direction_code(self.original.direction);
                self.modal_result = Some(ModalResult::Cancel);
            }
        }
        Task::none()
    }

    pub const fn commit_to(&self, value: &mut PinPropertiesValue) -> bool {
        if !matches!(self.modal_result, Some(ModalResult::Accept)) {
            return false;
        }
        *value = self.working;
        true
    }

    #[must_use]
    pub const fn buttons(&self) -> &DirectionButtons {
        &self.buttons
    }

    #[must_use]
    pub fn view(&self) -> Element<'_, PinPropertiesMessage> {
        let mut direction_row = row![text("Direction")].spacing(6);
        for direction in PinDirection::ALL {
            let label = if self.buttons.is_down(direction) {
                format!("[{}]", direction.label())
            } else {
                direction.label().to_owned()
            };
            direction_row = direction_row.push(
                button(text(label)).on_press(PinPropertiesMessage::DirectionPressed(direction)),
            );
        }
        let content = column![
            text(PIN_PROPERTIES_TITLE).size(18),
            direction_row,
            row![
                button("OK").on_press(PinPropertiesMessage::Accept),
                button("Cancel").on_press(PinPropertiesMessage::Cancel)
            ]
            .spacing(8),
        ]
        .spacing(10);
        container(content)
            .padding(16)
            .width(Length::Fill)
            .height(Length::Fill)
            .into()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    struct PickerError;

    struct Picker {
        result: Result<bool, PickerError>,
        calls: u32,
    }

    impl FontPicker for Picker {
        type Error = PickerError;

        fn execute(&mut self) -> Result<bool, Self::Error> {
            self.calls = self.calls.saturating_add(1);
            self.result
        }
    }

    fn text_value() -> ShapeTextValue {
        ShapeTextValue {
            text: "label".to_owned(),
            font: ShapeFontValue {
                family: "Arial".to_owned(),
                point_size: 10,
                style: FontStyle::Regular,
            },
        }
    }

    #[test]
    fn font_picker_accept_and_cancel_results_are_both_ignored() {
        let original = text_value();
        for accepted in [false, true] {
            let mut window = TextPropertiesWindow::new(original.clone());
            let mut picker = Picker {
                result: Ok(accepted),
                calls: 0,
            };
            assert!(window.open_font_picker(&mut picker).is_ok());
            assert_eq!(picker.calls, 1);
            assert_eq!(window.working(), &original);
        }
    }

    #[test]
    fn pending_font_request_executes_once_and_errors_propagate() {
        let mut window = TextPropertiesWindow::new(text_value());
        let _ = window.update(TextPropertiesMessage::FontPressed);
        let mut picker = Picker {
            result: Err(PickerError),
            calls: 0,
        };
        assert_eq!(
            window.run_pending_font_picker(&mut picker),
            Err(PickerError)
        );
        assert_eq!(picker.calls, 1);
        assert!(window.font_picker_requested());
    }

    #[test]
    fn reader_uses_recovered_precedence_and_defaults_to_east() {
        let mut buttons = DirectionButtons::default();
        assert_eq!(buttons.selected_direction_code(), DirectionCode(0));
        buttons.down = [true, true, true, true];
        assert_eq!(buttons.selected_direction_code(), DirectionCode(3));
        buttons.down = [false, false, true, true];
        assert_eq!(buttons.selected_direction_code(), DirectionCode(1));
    }

    #[test]
    fn set_if_changed_avoids_repeated_speed_button_setter_calls() {
        let mut buttons = DirectionButtons::default();
        assert!(buttons.set_button_if_changed(PinDirection::East, true));
        assert!(!buttons.set_button_if_changed(PinDirection::East, true));
        assert_eq!(buttons.setter_call_count(PinDirection::East), 1);
    }

    #[test]
    fn direction_codes_select_one_button_and_unsupported_code_clears_all() {
        let mut buttons = DirectionButtons::default();
        for direction in PinDirection::ALL {
            buttons.apply_direction_code(DirectionCode(direction.code()));
            assert!(buttons.is_down(direction));
            assert!(
                PinDirection::ALL
                    .into_iter()
                    .filter(|candidate| *candidate != direction)
                    .all(|candidate| !buttons.is_down(candidate))
            );
        }
        buttons.apply_direction_code(DirectionCode(99));
        assert!(
            PinDirection::ALL
                .into_iter()
                .all(|direction| !buttons.is_down(direction))
        );
    }

    #[test]
    fn click_router_ignores_other_sender_and_uses_speed_button_tag_low_byte() {
        let mut buttons = DirectionButtons::default();
        buttons.apply_direction_code(DirectionCode(0));
        assert!(!buttons.route_direction_click(DirectionSender::Other));
        assert_eq!(buttons.selected_direction_code(), DirectionCode(0));
        assert!(buttons.route_direction_click(DirectionSender::SpeedButton { tag: 0x103 }));
        assert_eq!(buttons.selected_direction_code(), DirectionCode(3));
        assert!(buttons.route_direction_click(DirectionSender::SpeedButton { tag: 0xff }));
        assert!(
            PinDirection::ALL
                .into_iter()
                .all(|direction| !buttons.is_down(direction))
        );
    }

    #[test]
    fn pin_window_stages_direction_and_commits_only_after_accept() {
        let original = PinPropertiesValue {
            direction: DirectionCode(2),
        };
        let mut caller = original;
        let mut window = PinPropertiesWindow::new(original);
        let _ = window.update(PinPropertiesMessage::DirectionPressed(PinDirection::North));
        assert!(!window.commit_to(&mut caller));
        assert_eq!(caller, original);
        let _ = window.update(PinPropertiesMessage::Accept);
        assert!(window.commit_to(&mut caller));
        assert_eq!(caller.direction, DirectionCode(3));
    }
}
