//! Packaged editable SVG defaults. Paths refer only to TIARA-owned artwork.

pub const COMMANDS: &[(&str, &[u8])] = &[
    ("ai", include_bytes!("../../../../glyph/commands/ai.svg")),
    ("arc", include_bytes!("../../../../glyph/commands/arc.svg")),
    (
        "arrow",
        include_bytes!("../../../../glyph/commands/arrow.svg"),
    ),
    (
        "book",
        include_bytes!("../../../../glyph/commands/book.svg"),
    ),
    ("bus", include_bytes!("../../../../glyph/commands/bus.svg")),
    (
        "chart",
        include_bytes!("../../../../glyph/commands/chart.svg"),
    ),
    (
        "check",
        include_bytes!("../../../../glyph/commands/check.svg"),
    ),
    (
        "chevron-right",
        include_bytes!("../../../../glyph/commands/chevron-right.svg"),
    ),
    (
        "close",
        include_bytes!("../../../../glyph/commands/close.svg"),
    ),
    (
        "cloud",
        include_bytes!("../../../../glyph/commands/cloud.svg"),
    ),
    (
        "command",
        include_bytes!("../../../../glyph/commands/command.svg"),
    ),
    (
        "component",
        include_bytes!("../../../../glyph/commands/component.svg"),
    ),
    (
        "copy",
        include_bytes!("../../../../glyph/commands/copy.svg"),
    ),
    (
        "cube",
        include_bytes!("../../../../glyph/commands/cube.svg"),
    ),
    ("cut", include_bytes!("../../../../glyph/commands/cut.svg")),
    (
        "delete",
        include_bytes!("../../../../glyph/commands/delete.svg"),
    ),
    (
        "digital",
        include_bytes!("../../../../glyph/commands/digital.svg"),
    ),
    (
        "download",
        include_bytes!("../../../../glyph/commands/download.svg"),
    ),
    (
        "ellipse",
        include_bytes!("../../../../glyph/commands/ellipse.svg"),
    ),
    (
        "equation",
        include_bytes!("../../../../glyph/commands/equation.svg"),
    ),
    (
        "export",
        include_bytes!("../../../../glyph/commands/export.svg"),
    ),
    (
        "fault",
        include_bytes!("../../../../glyph/commands/fault.svg"),
    ),
    (
        "filter",
        include_bytes!("../../../../glyph/commands/filter.svg"),
    ),
    ("fit", include_bytes!("../../../../glyph/commands/fit.svg")),
    (
        "flow",
        include_bytes!("../../../../glyph/commands/flow.svg"),
    ),
    (
        "grid",
        include_bytes!("../../../../glyph/commands/grid.svg"),
    ),
    (
        "help",
        include_bytes!("../../../../glyph/commands/help.svg"),
    ),
    (
        "image",
        include_bytes!("../../../../glyph/commands/image.svg"),
    ),
    (
        "import",
        include_bytes!("../../../../glyph/commands/import.svg"),
    ),
    (
        "info",
        include_bytes!("../../../../glyph/commands/info.svg"),
    ),
    (
        "input",
        include_bytes!("../../../../glyph/commands/input.svg"),
    ),
    (
        "junction",
        include_bytes!("../../../../glyph/commands/junction.svg"),
    ),
    (
        "label",
        include_bytes!("../../../../glyph/commands/label.svg"),
    ),
    (
        "layers",
        include_bytes!("../../../../glyph/commands/layers.svg"),
    ),
    (
        "library",
        include_bytes!("../../../../glyph/commands/library.svg"),
    ),
    (
        "line",
        include_bytes!("../../../../glyph/commands/line.svg"),
    ),
    (
        "lock",
        include_bytes!("../../../../glyph/commands/lock.svg"),
    ),
    (
        "meter",
        include_bytes!("../../../../glyph/commands/meter.svg"),
    ),
    (
        "mirror",
        include_bytes!("../../../../glyph/commands/mirror.svg"),
    ),
    ("new", include_bytes!("../../../../glyph/commands/new.svg")),
    (
        "open",
        include_bytes!("../../../../glyph/commands/open.svg"),
    ),
    (
        "output",
        include_bytes!("../../../../glyph/commands/output.svg"),
    ),
    (
        "page",
        include_bytes!("../../../../glyph/commands/page.svg"),
    ),
    (
        "paste",
        include_bytes!("../../../../glyph/commands/paste.svg"),
    ),
    ("pcb", include_bytes!("../../../../glyph/commands/pcb.svg")),
    (
        "polygon",
        include_bytes!("../../../../glyph/commands/polygon.svg"),
    ),
    (
        "power",
        include_bytes!("../../../../glyph/commands/power.svg"),
    ),
    (
        "print",
        include_bytes!("../../../../glyph/commands/print.svg"),
    ),
    (
        "probe",
        include_bytes!("../../../../glyph/commands/probe.svg"),
    ),
    (
        "rectangle",
        include_bytes!("../../../../glyph/commands/rectangle.svg"),
    ),
    (
        "redo",
        include_bytes!("../../../../glyph/commands/redo.svg"),
    ),
    (
        "refresh",
        include_bytes!("../../../../glyph/commands/refresh.svg"),
    ),
    (
        "rotate-left",
        include_bytes!("../../../../glyph/commands/rotate-left.svg"),
    ),
    (
        "rotate-right",
        include_bytes!("../../../../glyph/commands/rotate-right.svg"),
    ),
    ("run", include_bytes!("../../../../glyph/commands/run.svg")),
    (
        "run-again",
        include_bytes!("../../../../glyph/commands/run-again.svg"),
    ),
    (
        "save",
        include_bytes!("../../../../glyph/commands/save.svg"),
    ),
    (
        "save-all",
        include_bytes!("../../../../glyph/commands/save-all.svg"),
    ),
    (
        "save-as",
        include_bytes!("../../../../glyph/commands/save-as.svg"),
    ),
    (
        "scope",
        include_bytes!("../../../../glyph/commands/scope.svg"),
    ),
    (
        "select",
        include_bytes!("../../../../glyph/commands/select.svg"),
    ),
    (
        "select-all",
        include_bytes!("../../../../glyph/commands/select-all.svg"),
    ),
    (
        "settings",
        include_bytes!("../../../../glyph/commands/settings.svg"),
    ),
    (
        "spectrum",
        include_bytes!("../../../../glyph/commands/spectrum.svg"),
    ),
    (
        "stop",
        include_bytes!("../../../../glyph/commands/stop.svg"),
    ),
    (
        "table",
        include_bytes!("../../../../glyph/commands/table.svg"),
    ),
    (
        "target",
        include_bytes!("../../../../glyph/commands/target.svg"),
    ),
    (
        "temperature",
        include_bytes!("../../../../glyph/commands/temperature.svg"),
    ),
    (
        "terminal",
        include_bytes!("../../../../glyph/commands/terminal.svg"),
    ),
    (
        "text",
        include_bytes!("../../../../glyph/commands/text.svg"),
    ),
    (
        "undo",
        include_bytes!("../../../../glyph/commands/undo.svg"),
    ),
    (
        "unlock",
        include_bytes!("../../../../glyph/commands/unlock.svg"),
    ),
    (
        "upload",
        include_bytes!("../../../../glyph/commands/upload.svg"),
    ),
    (
        "wave",
        include_bytes!("../../../../glyph/commands/wave.svg"),
    ),
    ("web", include_bytes!("../../../../glyph/commands/web.svg")),
    (
        "wire",
        include_bytes!("../../../../glyph/commands/wire.svg"),
    ),
    (
        "zoom",
        include_bytes!("../../../../glyph/commands/zoom.svg"),
    ),
    (
        "zoom-in",
        include_bytes!("../../../../glyph/commands/zoom-in.svg"),
    ),
    (
        "zoom-out",
        include_bytes!("../../../../glyph/commands/zoom-out.svg"),
    ),
];

pub const COMPONENTS: &[(&str, &[u8])] = &[
    (
        "7 segment display 4 digit",
        include_bytes!("../../../../glyph/components/7 segment display 4 digit.svg"),
    ),
    (
        "Arduino",
        include_bytes!("../../../../glyph/components/Arduino.svg"),
    ),
    (
        "Arduino Shields",
        include_bytes!("../../../../glyph/components/Arduino Shields.svg"),
    ),
    (
        "EEPROM%2FROM",
        include_bytes!("../../../../glyph/components/EEPROM%2FROM.svg"),
    ),
    (
        "HDL",
        include_bytes!("../../../../glyph/components/HDL.svg"),
    ),
    (
        "Modules-Breakouts",
        include_bytes!("../../../../glyph/components/Modules-Breakouts.svg"),
    ),
    (
        "SPI",
        include_bytes!("../../../../glyph/components/SPI.svg"),
    ),
    (
        "id_component_2_terminal_phototransistor",
        include_bytes!("../../../../glyph/components/id_component_2_terminal_phototransistor.svg"),
    ),
    (
        "id_component_3-state_buffer",
        include_bytes!("../../../../glyph/components/id_component_3-state_buffer.svg"),
    ),
    (
        "id_component_3_terminal_phototransistor",
        include_bytes!("../../../../glyph/components/id_component_3_terminal_phototransistor.svg"),
    ),
    (
        "id_component_4_terminal_mosfets",
        include_bytes!("../../../../glyph/components/id_component_4_terminal_mosfets.svg"),
    ),
    (
        "id_component_555_timer",
        include_bytes!("../../../../glyph/components/id_component_555_timer.svg"),
    ),
    (
        "id_component_7_segment_display",
        include_bytes!("../../../../glyph/components/id_component_7_segment_display.svg"),
    ),
    (
        "id_component_PIR_sensor",
        include_bytes!("../../../../glyph/components/id_component_PIR_sensor.svg"),
    ),
    (
        "id_component_a_matrix",
        include_bytes!("../../../../glyph/components/id_component_a_matrix.svg"),
    ),
    (
        "id_component_ad_converters",
        include_bytes!("../../../../glyph/components/id_component_ad_converters.svg"),
    ),
    (
        "id_component_add_sub_mult_div",
        include_bytes!("../../../../glyph/components/id_component_add_sub_mult_div.svg"),
    ),
    (
        "id_component_alternate_switch",
        include_bytes!("../../../../glyph/components/id_component_alternate_switch.svg"),
    ),
    (
        "id_component_amper_meter",
        include_bytes!("../../../../glyph/components/id_component_amper_meter.svg"),
    ),
    (
        "id_component_ampere_meter",
        include_bytes!("../../../../glyph/components/id_component_ampere_meter.svg"),
    ),
    (
        "id_component_analog_multiplexers",
        include_bytes!("../../../../glyph/components/id_component_analog_multiplexers.svg"),
    ),
    (
        "id_component_analog_switches",
        include_bytes!("../../../../glyph/components/id_component_analog_switches.svg"),
    ),
    (
        "id_component_and2_gate",
        include_bytes!("../../../../glyph/components/id_component_and2_gate.svg"),
    ),
    (
        "id_component_and3_gate",
        include_bytes!("../../../../glyph/components/id_component_and3_gate.svg"),
    ),
    (
        "id_component_and4_gate",
        include_bytes!("../../../../glyph/components/id_component_and4_gate.svg"),
    ),
    (
        "id_component_arithmetic_circuits",
        include_bytes!("../../../../glyph/components/id_component_arithmetic_circuits.svg"),
    ),
    (
        "id_component_ascii_display",
        include_bytes!("../../../../glyph/components/id_component_ascii_display.svg"),
    ),
    (
        "id_component_ascii_key",
        include_bytes!("../../../../glyph/components/id_component_ascii_key.svg"),
    ),
    (
        "id_component_average_meter",
        include_bytes!("../../../../glyph/components/id_component_average_meter.svg"),
    ),
    (
        "id_component_b_matrix",
        include_bytes!("../../../../glyph/components/id_component_b_matrix.svg"),
    ),
    (
        "id_component_basic_ic_packages",
        include_bytes!("../../../../glyph/components/id_component_basic_ic_packages.svg"),
    ),
    (
        "id_component_battery",
        include_bytes!("../../../../glyph/components/id_component_battery.svg"),
    ),
    (
        "id_component_bridge",
        include_bytes!("../../../../glyph/components/id_component_bridge.svg"),
    ),
    (
        "id_component_bridge_rectifier",
        include_bytes!("../../../../glyph/components/id_component_bridge_rectifier.svg"),
    ),
    (
        "id_component_buffer",
        include_bytes!("../../../../glyph/components/id_component_buffer.svg"),
    ),
    (
        "id_component_buffers",
        include_bytes!("../../../../glyph/components/id_component_buffers.svg"),
    ),
    (
        "id_component_buffers___drivers",
        include_bytes!("../../../../glyph/components/id_component_buffers___drivers.svg"),
    ),
    (
        "id_component_bulb",
        include_bytes!("../../../../glyph/components/id_component_bulb.svg"),
    ),
    (
        "id_component_bus_display",
        include_bytes!("../../../../glyph/components/id_component_bus_display.svg"),
    ),
    (
        "id_component_calculator_keypad",
        include_bytes!("../../../../glyph/components/id_component_calculator_keypad.svg"),
    ),
    (
        "id_component_capacitor",
        include_bytes!("../../../../glyph/components/id_component_capacitor.svg"),
    ),
    (
        "id_component_changeover_push_button",
        include_bytes!("../../../../glyph/components/id_component_changeover_push_button.svg"),
    ),
    (
        "id_component_changeover_switch",
        include_bytes!("../../../../glyph/components/id_component_changeover_switch.svg"),
    ),
    (
        "id_component_charged_capacitor",
        include_bytes!("../../../../glyph/components/id_component_charged_capacitor.svg"),
    ),
    (
        "id_component_clock",
        include_bytes!("../../../../glyph/components/id_component_clock.svg"),
    ),
    (
        "id_component_clock2",
        include_bytes!("../../../../glyph/components/id_component_clock2.svg"),
    ),
    (
        "id_component_closed_push_button",
        include_bytes!("../../../../glyph/components/id_component_closed_push_button.svg"),
    ),
    (
        "id_component_comparators",
        include_bytes!("../../../../glyph/components/id_component_comparators.svg"),
    ),
    (
        "id_component_connectors",
        include_bytes!("../../../../glyph/components/id_component_connectors.svg"),
    ),
    (
        "id_component_controlled_sources",
        include_bytes!("../../../../glyph/components/id_component_controlled_sources.svg"),
    ),
    (
        "id_component_controllers",
        include_bytes!("../../../../glyph/components/id_component_controllers.svg"),
    ),
    (
        "id_component_counters",
        include_bytes!("../../../../glyph/components/id_component_counters.svg"),
    ),
    (
        "id_component_coupled_inductors",
        include_bytes!("../../../../glyph/components/id_component_coupled_inductors.svg"),
    ),
    (
        "id_component_current_arrow",
        include_bytes!("../../../../glyph/components/id_component_current_arrow.svg"),
    ),
    (
        "id_component_current_generator",
        include_bytes!("../../../../glyph/components/id_component_current_generator.svg"),
    ),
    (
        "id_component_current_shunt_monitors",
        include_bytes!("../../../../glyph/components/id_component_current_shunt_monitors.svg"),
    ),
    (
        "id_component_current_source",
        include_bytes!("../../../../glyph/components/id_component_current_source.svg"),
    ),
    (
        "id_component_d_flipflop",
        include_bytes!("../../../../glyph/components/id_component_d_flipflop.svg"),
    ),
    (
        "id_component_da_converters",
        include_bytes!("../../../../glyph/components/id_component_da_converters.svg"),
    ),
    (
        "id_component_data_generator_4-bit",
        include_bytes!("../../../../glyph/components/id_component_data_generator_4-bit.svg"),
    ),
    (
        "id_component_data_generator_8-bit",
        include_bytes!("../../../../glyph/components/id_component_data_generator_8-bit.svg"),
    ),
    (
        "id_component_data_selectors_multiplexers",
        include_bytes!("../../../../glyph/components/id_component_data_selectors_multiplexers.svg"),
    ),
    (
        "id_component_dead_time_blocks",
        include_bytes!("../../../../glyph/components/id_component_dead_time_blocks.svg"),
    ),
    (
        "id_component_decoders_demultiplexers",
        include_bytes!("../../../../glyph/components/id_component_decoders_demultiplexers.svg"),
    ),
    (
        "id_component_delta",
        include_bytes!("../../../../glyph/components/id_component_delta.svg"),
    ),
    (
        "id_component_diac",
        include_bytes!("../../../../glyph/components/id_component_diac.svg"),
    ),
    (
        "id_component_difference_amplifiers",
        include_bytes!("../../../../glyph/components/id_component_difference_amplifiers.svg"),
    ),
    (
        "id_component_digital_crystal",
        include_bytes!("../../../../glyph/components/id_component_digital_crystal.svg"),
    ),
    (
        "id_component_digital_high_source",
        include_bytes!("../../../../glyph/components/id_component_digital_high_source.svg"),
    ),
    (
        "id_component_digital_low_source",
        include_bytes!("../../../../glyph/components/id_component_digital_low_source.svg"),
    ),
    (
        "id_component_digital_multivibrators",
        include_bytes!("../../../../glyph/components/id_component_digital_multivibrators.svg"),
    ),
    (
        "id_component_digital_voltage_source",
        include_bytes!("../../../../glyph/components/id_component_digital_voltage_source.svg"),
    ),
    (
        "id_component_diode",
        include_bytes!("../../../../glyph/components/id_component_diode.svg"),
    ),
    (
        "id_component_diode_arrays",
        include_bytes!("../../../../glyph/components/id_component_diode_arrays.svg"),
    ),
    (
        "id_component_diodes",
        include_bytes!("../../../../glyph/components/id_component_diodes.svg"),
    ),
    (
        "id_component_dip_switches",
        include_bytes!("../../../../glyph/components/id_component_dip_switches.svg"),
    ),
    (
        "id_component_display_16-bit",
        include_bytes!("../../../../glyph/components/id_component_display_16-bit.svg"),
    ),
    (
        "id_component_double_pole_changeover_relay",
        include_bytes!(
            "../../../../glyph/components/id_component_double_pole_changeover_relay.svg"
        ),
    ),
    (
        "id_component_double_pole_open_relay",
        include_bytes!("../../../../glyph/components/id_component_double_pole_open_relay.svg"),
    ),
    (
        "id_component_efficiency_meter",
        include_bytes!("../../../../glyph/components/id_component_efficiency_meter.svg"),
    ),
    (
        "id_component_energy_storing_inductor",
        include_bytes!("../../../../glyph/components/id_component_energy_storing_inductor.svg"),
    ),
    (
        "id_component_flip-flops___latches",
        include_bytes!("../../../../glyph/components/id_component_flip-flops___latches.svg"),
    ),
    (
        "id_component_fpga_pin",
        include_bytes!("../../../../glyph/components/id_component_fpga_pin.svg"),
    ),
    (
        "id_component_frequency_meter",
        include_bytes!("../../../../glyph/components/id_component_frequency_meter.svg"),
    ),
    (
        "id_component_fully-differential_amplifiers",
        include_bytes!(
            "../../../../glyph/components/id_component_fully-differential_amplifiers.svg"
        ),
    ),
    (
        "id_component_fuse",
        include_bytes!("../../../../glyph/components/id_component_fuse.svg"),
    ),
    (
        "id_component_g_matrix",
        include_bytes!("../../../../glyph/components/id_component_g_matrix.svg"),
    ),
    (
        "id_component_gaasfet",
        include_bytes!("../../../../glyph/components/id_component_gaasfet.svg"),
    ),
    (
        "id_component_ganfet",
        include_bytes!("../../../../glyph/components/id_component_ganfet.svg"),
    ),
    (
        "id_component_gates",
        include_bytes!("../../../../glyph/components/id_component_gates.svg"),
    ),
    (
        "id_component_glcd_display",
        include_bytes!("../../../../glyph/components/id_component_glcd_display.svg"),
    ),
    (
        "id_component_ground",
        include_bytes!("../../../../glyph/components/id_component_ground.svg"),
    ),
    (
        "id_component_h_matrix",
        include_bytes!("../../../../glyph/components/id_component_h_matrix.svg"),
    ),
    (
        "id_component_hex_display",
        include_bytes!("../../../../glyph/components/id_component_hex_display.svg"),
    ),
    (
        "id_component_hex_key",
        include_bytes!("../../../../glyph/components/id_component_hex_key.svg"),
    ),
    (
        "id_component_hex_keypad",
        include_bytes!("../../../../glyph/components/id_component_hex_keypad.svg"),
    ),
    (
        "id_component_high-low_switch",
        include_bytes!("../../../../glyph/components/id_component_high-low_switch.svg"),
    ),
    (
        "id_component_ideal_adc",
        include_bytes!("../../../../glyph/components/id_component_ideal_adc.svg"),
    ),
    (
        "id_component_ideal_dac",
        include_bytes!("../../../../glyph/components/id_component_ideal_dac.svg"),
    ),
    (
        "id_component_ideal_op._amplifier",
        include_bytes!("../../../../glyph/components/id_component_ideal_op._amplifier.svg"),
    ),
    (
        "id_component_igbt",
        include_bytes!("../../../../glyph/components/id_component_igbt.svg"),
    ),
    (
        "id_component_impedance",
        include_bytes!("../../../../glyph/components/id_component_impedance.svg"),
    ),
    (
        "id_component_impedance_meter",
        include_bytes!("../../../../glyph/components/id_component_impedance_meter.svg"),
    ),
    (
        "id_component_inductive_coupling",
        include_bytes!("../../../../glyph/components/id_component_inductive_coupling.svg"),
    ),
    (
        "id_component_inductor",
        include_bytes!("../../../../glyph/components/id_component_inductor.svg"),
    ),
    (
        "id_component_inductors",
        include_bytes!("../../../../glyph/components/id_component_inductors.svg"),
    ),
    (
        "id_component_infrared_sensor",
        include_bytes!("../../../../glyph/components/id_component_infrared_sensor.svg"),
    ),
    (
        "id_component_initial_condition1",
        include_bytes!("../../../../glyph/components/id_component_initial_condition1.svg"),
    ),
    (
        "id_component_initial_condition2",
        include_bytes!("../../../../glyph/components/id_component_initial_condition2.svg"),
    ),
    (
        "id_component_instrumentation_amplifiers",
        include_bytes!("../../../../glyph/components/id_component_instrumentation_amplifiers.svg"),
    ),
    (
        "id_component_interface",
        include_bytes!("../../../../glyph/components/id_component_interface.svg"),
    ),
    (
        "id_component_inverter",
        include_bytes!("../../../../glyph/components/id_component_inverter.svg"),
    ),
    (
        "id_component_jk_flipflop",
        include_bytes!("../../../../glyph/components/id_component_jk_flipflop.svg"),
    ),
    (
        "id_component_jk_flipflop_with_clear",
        include_bytes!("../../../../glyph/components/id_component_jk_flipflop_with_clear.svg"),
    ),
    (
        "id_component_jk_flipflop_with_preset",
        include_bytes!("../../../../glyph/components/id_component_jk_flipflop_with_preset.svg"),
    ),
    (
        "id_component_jumper",
        include_bytes!("../../../../glyph/components/id_component_jumper.svg"),
    ),
    (
        "id_component_junction_fet_n-channel",
        include_bytes!("../../../../glyph/components/id_component_junction_fet_n-channel.svg"),
    ),
    (
        "id_component_junction_fet_p-channel",
        include_bytes!("../../../../glyph/components/id_component_junction_fet_p-channel.svg"),
    ),
    (
        "id_component_k_matrix",
        include_bytes!("../../../../glyph/components/id_component_k_matrix.svg"),
    ),
    (
        "id_component_lag_blocks",
        include_bytes!("../../../../glyph/components/id_component_lag_blocks.svg"),
    ),
    (
        "id_component_latch",
        include_bytes!("../../../../glyph/components/id_component_latch.svg"),
    ),
    (
        "id_component_lcd_display",
        include_bytes!("../../../../glyph/components/id_component_lcd_display.svg"),
    ),
    (
        "id_component_lcd_display2",
        include_bytes!("../../../../glyph/components/id_component_lcd_display2.svg"),
    ),
    (
        "id_component_leds",
        include_bytes!("../../../../glyph/components/id_component_leds.svg"),
    ),
    (
        "id_component_light_sensor",
        include_bytes!("../../../../glyph/components/id_component_light_sensor.svg"),
    ),
    (
        "id_component_logic_comparators",
        include_bytes!("../../../../glyph/components/id_component_logic_comparators.svg"),
    ),
    (
        "id_component_logic_indicator",
        include_bytes!("../../../../glyph/components/id_component_logic_indicator.svg"),
    ),
    (
        "id_component_logic_indicator2",
        include_bytes!("../../../../glyph/components/id_component_logic_indicator2.svg"),
    ),
    (
        "id_component_lossy_capacitor",
        include_bytes!("../../../../glyph/components/id_component_lossy_capacitor.svg"),
    ),
    (
        "id_component_macro_pin",
        include_bytes!("../../../../glyph/components/id_component_macro_pin.svg"),
    ),
    (
        "id_component_magnetic_core",
        include_bytes!("../../../../glyph/components/id_component_magnetic_core.svg"),
    ),
    (
        "id_component_mcu",
        include_bytes!("../../../../glyph/components/id_component_mcu.svg"),
    ),
    (
        "id_component_memory",
        include_bytes!("../../../../glyph/components/id_component_memory.svg"),
    ),
    (
        "id_component_microphones",
        include_bytes!("../../../../glyph/components/id_component_microphones.svg"),
    ),
    (
        "id_component_microstrip",
        include_bytes!("../../../../glyph/components/id_component_microstrip.svg"),
    ),
    (
        "id_component_microstrip_open_ended",
        include_bytes!("../../../../glyph/components/id_component_microstrip_open_ended.svg"),
    ),
    (
        "id_component_microstrip_shorted",
        include_bytes!("../../../../glyph/components/id_component_microstrip_shorted.svg"),
    ),
    (
        "id_component_motor",
        include_bytes!("../../../../glyph/components/id_component_motor.svg"),
    ),
    (
        "id_component_mounting_hole",
        include_bytes!("../../../../glyph/components/id_component_mounting_hole.svg"),
    ),
    (
        "id_component_multimeters",
        include_bytes!("../../../../glyph/components/id_component_multimeters.svg"),
    ),
    (
        "id_component_n-channel_jfet",
        include_bytes!("../../../../glyph/components/id_component_n-channel_jfet.svg"),
    ),
    (
        "id_component_n-channel_mos",
        include_bytes!("../../../../glyph/components/id_component_n-channel_mos.svg"),
    ),
    (
        "id_component_nand2_gate",
        include_bytes!("../../../../glyph/components/id_component_nand2_gate.svg"),
    ),
    (
        "id_component_nand3_gate",
        include_bytes!("../../../../glyph/components/id_component_nand3_gate.svg"),
    ),
    (
        "id_component_nand4_gate",
        include_bytes!("../../../../glyph/components/id_component_nand4_gate.svg"),
    ),
    (
        "id_component_network_analyser",
        include_bytes!("../../../../glyph/components/id_component_network_analyser.svg"),
    ),
    (
        "id_component_nmos_depletion-type",
        include_bytes!("../../../../glyph/components/id_component_nmos_depletion-type.svg"),
    ),
    (
        "id_component_nmos_enhancement-type",
        include_bytes!("../../../../glyph/components/id_component_nmos_enhancement-type.svg"),
    ),
    (
        "id_component_nodeset1",
        include_bytes!("../../../../glyph/components/id_component_nodeset1.svg"),
    ),
    (
        "id_component_nodeset2",
        include_bytes!("../../../../glyph/components/id_component_nodeset2.svg"),
    ),
    (
        "id_component_nonlinear_blocks",
        include_bytes!("../../../../glyph/components/id_component_nonlinear_blocks.svg"),
    ),
    (
        "id_component_nonlinear_inductors",
        include_bytes!("../../../../glyph/components/id_component_nonlinear_inductors.svg"),
    ),
    (
        "id_component_nor2_gate",
        include_bytes!("../../../../glyph/components/id_component_nor2_gate.svg"),
    ),
    (
        "id_component_nor3_gate",
        include_bytes!("../../../../glyph/components/id_component_nor3_gate.svg"),
    ),
    (
        "id_component_nor4_gate",
        include_bytes!("../../../../glyph/components/id_component_nor4_gate.svg"),
    ),
    (
        "id_component_npn_bipolar_transistor",
        include_bytes!("../../../../glyph/components/id_component_npn_bipolar_transistor.svg"),
    ),
    (
        "id_component_npn_bipolar_transistors",
        include_bytes!("../../../../glyph/components/id_component_npn_bipolar_transistors.svg"),
    ),
    (
        "id_component_npn_darlington_transistors",
        include_bytes!("../../../../glyph/components/id_component_npn_darlington_transistors.svg"),
    ),
    (
        "id_component_npn_rf_bipolar_transistors",
        include_bytes!("../../../../glyph/components/id_component_npn_rf_bipolar_transistors.svg"),
    ),
    (
        "id_component_ohmmeter",
        include_bytes!("../../../../glyph/components/id_component_ohmmeter.svg"),
    ),
    (
        "id_component_open_circuit",
        include_bytes!("../../../../glyph/components/id_component_open_circuit.svg"),
    ),
    (
        "id_component_open_push_button",
        include_bytes!("../../../../glyph/components/id_component_open_push_button.svg"),
    ),
    (
        "id_component_operational_amplifier",
        include_bytes!("../../../../glyph/components/id_component_operational_amplifier.svg"),
    ),
    (
        "id_component_operational_amplifiers",
        include_bytes!("../../../../glyph/components/id_component_operational_amplifiers.svg"),
    ),
    (
        "id_component_optocouplers",
        include_bytes!("../../../../glyph/components/id_component_optocouplers.svg"),
    ),
    (
        "id_component_or2_gate",
        include_bytes!("../../../../glyph/components/id_component_or2_gate.svg"),
    ),
    (
        "id_component_or3_gate",
        include_bytes!("../../../../glyph/components/id_component_or3_gate.svg"),
    ),
    (
        "id_component_or4_gate",
        include_bytes!("../../../../glyph/components/id_component_or4_gate.svg"),
    ),
    (
        "id_component_oscilloscopes",
        include_bytes!("../../../../glyph/components/id_component_oscilloscopes.svg"),
    ),
    (
        "id_component_other_components",
        include_bytes!("../../../../glyph/components/id_component_other_components.svg"),
    ),
    (
        "id_component_p-channel_jfet",
        include_bytes!("../../../../glyph/components/id_component_p-channel_jfet.svg"),
    ),
    (
        "id_component_p-channel_mos",
        include_bytes!("../../../../glyph/components/id_component_p-channel_mos.svg"),
    ),
    (
        "id_component_photodiode",
        include_bytes!("../../../../glyph/components/id_component_photodiode.svg"),
    ),
    (
        "id_component_photoresistor",
        include_bytes!("../../../../glyph/components/id_component_photoresistor.svg"),
    ),
    (
        "id_component_pin_diode_1p",
        include_bytes!("../../../../glyph/components/id_component_pin_diode_1p.svg"),
    ),
    (
        "id_component_pin_diode_2p",
        include_bytes!("../../../../glyph/components/id_component_pin_diode_2p.svg"),
    ),
    (
        "id_component_pmos_depletion-type",
        include_bytes!("../../../../glyph/components/id_component_pmos_depletion-type.svg"),
    ),
    (
        "id_component_pmos_enhancement-type",
        include_bytes!("../../../../glyph/components/id_component_pmos_enhancement-type.svg"),
    ),
    (
        "id_component_pnp_bipolar_transistor",
        include_bytes!("../../../../glyph/components/id_component_pnp_bipolar_transistor.svg"),
    ),
    (
        "id_component_pnp_bipolar_transistors",
        include_bytes!("../../../../glyph/components/id_component_pnp_bipolar_transistors.svg"),
    ),
    (
        "id_component_pnp_darlington_transistors",
        include_bytes!("../../../../glyph/components/id_component_pnp_darlington_transistors.svg"),
    ),
    (
        "id_component_pnp_rf_bipolar_transistors",
        include_bytes!("../../../../glyph/components/id_component_pnp_rf_bipolar_transistors.svg"),
    ),
    (
        "id_component_potentiometer",
        include_bytes!("../../../../glyph/components/id_component_potentiometer.svg"),
    ),
    (
        "id_component_power_meter",
        include_bytes!("../../../../glyph/components/id_component_power_meter.svg"),
    ),
    (
        "id_component_pull_up_down_resistor",
        include_bytes!("../../../../glyph/components/id_component_pull_up_down_resistor.svg"),
    ),
    (
        "id_component_pull_up_resistor",
        include_bytes!("../../../../glyph/components/id_component_pull_up_resistor.svg"),
    ),
    (
        "id_component_pulse_source",
        include_bytes!("../../../../glyph/components/id_component_pulse_source.svg"),
    ),
    (
        "id_component_pulse_source2",
        include_bytes!("../../../../glyph/components/id_component_pulse_source2.svg"),
    ),
    (
        "id_component_quartz_crystal",
        include_bytes!("../../../../glyph/components/id_component_quartz_crystal.svg"),
    ),
    (
        "id_component_real_ad_da",
        include_bytes!("../../../../glyph/components/id_component_real_ad_da.svg"),
    ),
    (
        "id_component_real_time_measurement_point",
        include_bytes!("../../../../glyph/components/id_component_real_time_measurement_point.svg"),
    ),
    (
        "id_component_registers",
        include_bytes!("../../../../glyph/components/id_component_registers.svg"),
    ),
    (
        "id_component_relay_coils",
        include_bytes!("../../../../glyph/components/id_component_relay_coils.svg"),
    ),
    (
        "id_component_relay_switches",
        include_bytes!("../../../../glyph/components/id_component_relay_switches.svg"),
    ),
    (
        "id_component_resistor",
        include_bytes!("../../../../glyph/components/id_component_resistor.svg"),
    ),
    (
        "id_component_resistor_networks",
        include_bytes!("../../../../glyph/components/id_component_resistor_networks.svg"),
    ),
    (
        "id_component_rf_capacitors",
        include_bytes!("../../../../glyph/components/id_component_rf_capacitors.svg"),
    ),
    (
        "id_component_rf_circulator",
        include_bytes!("../../../../glyph/components/id_component_rf_circulator.svg"),
    ),
    (
        "id_component_rf_direction_coupler",
        include_bytes!("../../../../glyph/components/id_component_rf_direction_coupler.svg"),
    ),
    (
        "id_component_rf_inductors_1p",
        include_bytes!("../../../../glyph/components/id_component_rf_inductors_1p.svg"),
    ),
    (
        "id_component_rf_inductors_2p",
        include_bytes!("../../../../glyph/components/id_component_rf_inductors_2p.svg"),
    ),
    (
        "id_component_rf_varicap_diode",
        include_bytes!("../../../../glyph/components/id_component_rf_varicap_diode.svg"),
    ),
    (
        "id_component_s_matrix",
        include_bytes!("../../../../glyph/components/id_component_s_matrix.svg"),
    ),
    (
        "id_component_schmidt_inverter",
        include_bytes!("../../../../glyph/components/id_component_schmidt_inverter.svg"),
    ),
    (
        "id_component_schottky_diode",
        include_bytes!("../../../../glyph/components/id_component_schottky_diode.svg"),
    ),
    (
        "id_component_second_order_lag_blocks",
        include_bytes!("../../../../glyph/components/id_component_second_order_lag_blocks.svg"),
    ),
    (
        "id_component_signal_analysers",
        include_bytes!("../../../../glyph/components/id_component_signal_analysers.svg"),
    ),
    (
        "id_component_single_pole_changeover_relay",
        include_bytes!(
            "../../../../glyph/components/id_component_single_pole_changeover_relay.svg"
        ),
    ),
    (
        "id_component_single_pole_closed_relay",
        include_bytes!("../../../../glyph/components/id_component_single_pole_closed_relay.svg"),
    ),
    (
        "id_component_single_pole_open_relay",
        include_bytes!("../../../../glyph/components/id_component_single_pole_open_relay.svg"),
    ),
    (
        "id_component_smps",
        include_bytes!("../../../../glyph/components/id_component_smps.svg"),
    ),
    (
        "id_component_solar_cell",
        include_bytes!("../../../../glyph/components/id_component_solar_cell.svg"),
    ),
    (
        "id_component_speaker",
        include_bytes!("../../../../glyph/components/id_component_speaker.svg"),
    ),
    (
        "id_component_sqvco",
        include_bytes!("../../../../glyph/components/id_component_sqvco.svg"),
    ),
    (
        "id_component_sr_flipflop",
        include_bytes!("../../../../glyph/components/id_component_sr_flipflop.svg"),
    ),
    (
        "id_component_star",
        include_bytes!("../../../../glyph/components/id_component_star.svg"),
    ),
    (
        "id_component_steady_state_sensor",
        include_bytes!("../../../../glyph/components/id_component_steady_state_sensor.svg"),
    ),
    (
        "id_component_steady_state_trigger",
        include_bytes!("../../../../glyph/components/id_component_steady_state_trigger.svg"),
    ),
    (
        "id_component_stepper_motor",
        include_bytes!("../../../../glyph/components/id_component_stepper_motor.svg"),
    ),
    (
        "id_component_svco",
        include_bytes!("../../../../glyph/components/id_component_svco.svg"),
    ),
    (
        "id_component_switch",
        include_bytes!("../../../../glyph/components/id_component_switch.svg"),
    ),
    (
        "id_component_switching_diode",
        include_bytes!("../../../../glyph/components/id_component_switching_diode.svg"),
    ),
    (
        "id_component_thermistors",
        include_bytes!("../../../../glyph/components/id_component_thermistors.svg"),
    ),
    (
        "id_component_thyristor",
        include_bytes!("../../../../glyph/components/id_component_thyristor.svg"),
    ),
    (
        "id_component_thyristors",
        include_bytes!("../../../../glyph/components/id_component_thyristors.svg"),
    ),
    (
        "id_component_time-controlled_alt_switch",
        include_bytes!("../../../../glyph/components/id_component_time-controlled_alt_switch.svg"),
    ),
    (
        "id_component_time-controlled_switch",
        include_bytes!("../../../../glyph/components/id_component_time-controlled_switch.svg"),
    ),
    (
        "id_component_timers",
        include_bytes!("../../../../glyph/components/id_component_timers.svg"),
    ),
    (
        "id_component_tinalabii",
        include_bytes!("../../../../glyph/components/id_component_tinalabii.svg"),
    ),
    (
        "id_component_traffic_light",
        include_bytes!("../../../../glyph/components/id_component_traffic_light.svg"),
    ),
    (
        "id_component_transformers",
        include_bytes!("../../../../glyph/components/id_component_transformers.svg"),
    ),
    (
        "id_component_transmission_lines",
        include_bytes!("../../../../glyph/components/id_component_transmission_lines.svg"),
    ),
    (
        "id_component_triac",
        include_bytes!("../../../../glyph/components/id_component_triac.svg"),
    ),
    (
        "id_component_tvco",
        include_bytes!("../../../../glyph/components/id_component_tvco.svg"),
    ),
    (
        "id_component_ultrasonic_sensor",
        include_bytes!("../../../../glyph/components/id_component_ultrasonic_sensor.svg"),
    ),
    (
        "id_component_vacuum_tubes",
        include_bytes!("../../../../glyph/components/id_component_vacuum_tubes.svg"),
    ),
    (
        "id_component_variable_capacitor",
        include_bytes!("../../../../glyph/components/id_component_variable_capacitor.svg"),
    ),
    (
        "id_component_variable_gain_amplifiers",
        include_bytes!("../../../../glyph/components/id_component_variable_gain_amplifiers.svg"),
    ),
    (
        "id_component_variable_inductor",
        include_bytes!("../../../../glyph/components/id_component_variable_inductor.svg"),
    ),
    (
        "id_component_varicap_diode",
        include_bytes!("../../../../glyph/components/id_component_varicap_diode.svg"),
    ),
    (
        "id_component_vco",
        include_bytes!("../../../../glyph/components/id_component_vco.svg"),
    ),
    (
        "id_component_volt_arrow",
        include_bytes!("../../../../glyph/components/id_component_volt_arrow.svg"),
    ),
    (
        "id_component_volt_meter",
        include_bytes!("../../../../glyph/components/id_component_volt_meter.svg"),
    ),
    (
        "id_component_voltage-controlled_switch",
        include_bytes!("../../../../glyph/components/id_component_voltage-controlled_switch.svg"),
    ),
    (
        "id_component_voltage-controlled_switch_with_hysteresis",
        include_bytes!(
            "../../../../glyph/components/id_component_voltage-controlled_switch_with_hysteresis.svg"
        ),
    ),
    (
        "id_component_voltage_generator",
        include_bytes!("../../../../glyph/components/id_component_voltage_generator.svg"),
    ),
    (
        "id_component_voltage_pin",
        include_bytes!("../../../../glyph/components/id_component_voltage_pin.svg"),
    ),
    (
        "id_component_voltage_references",
        include_bytes!("../../../../glyph/components/id_component_voltage_references.svg"),
    ),
    (
        "id_component_voltage_regulators",
        include_bytes!("../../../../glyph/components/id_component_voltage_regulators.svg"),
    ),
    (
        "id_component_voltage_source",
        include_bytes!("../../../../glyph/components/id_component_voltage_source.svg"),
    ),
    (
        "id_component_xor_gate",
        include_bytes!("../../../../glyph/components/id_component_xor_gate.svg"),
    ),
    (
        "id_component_z_matrix",
        include_bytes!("../../../../glyph/components/id_component_z_matrix.svg"),
    ),
    (
        "id_component_zener_diode",
        include_bytes!("../../../../glyph/components/id_component_zener_diode.svg"),
    ),
];
